// Code generated by go-asyncapi tool. DO NOT EDIT.

package operations

import (
	"context"
	"github.com/bdragon300/go-asyncapi/run"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/channels"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/messages"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
)

type ReceiveAuthResponseServerWs interface {
	OpenAuthWs(context.Context, run.AnySecurityScheme) (*channels.AuthWs, error)
	OpenReceiveAuthResponseWs(context.Context) (*ReceiveAuthResponseWs, error)
	Producer() ws.Producer
	Consumer() ws.Consumer
}

func OpenReceiveAuthResponseWs(
	ctx context.Context,
	server ReceiveAuthResponseServerWs,

) (*ReceiveAuthResponseWs, error) {
	ch, err := channels.OpenAuthWs(
		ctx,
		server,

		nil,
		nil,
	)
	if err != nil {
		return nil, err
	}

	return &ReceiveAuthResponseWs{
		Channel: ch,
	}, nil
}

type ReceiveAuthResponseChannelWs interface {
	Close() error

	SealServerMessage(ws.EnvelopeWriter, channels.AuthEnvelopeMarshalerWs) error
	PublishServerMessage(context.Context, channels.AuthEnvelopeMarshalerWs) error

	UnsealServerMessage(ws.EnvelopeReader, channels.AuthEnvelopeUnmarshalerWs) error
	SubscribeServerMessage(context.Context, func(messages.ServerMessageReceiver)) error
}

type ReceiveAuthResponseWs struct {
	Channel ReceiveAuthResponseChannelWs
}

func (c ReceiveAuthResponseWs) Close() error {
	return c.Channel.Close()
}

func (o ReceiveAuthResponseWs) UnsealServerMessage(
	envelope ws.EnvelopeReader,
	message channels.AuthEnvelopeUnmarshalerWs,
) error {
	return o.Channel.UnsealServerMessage(envelope, message)
}

func (o ReceiveAuthResponseWs) SubscribeServerMessage(
	ctx context.Context,
	cb func(message messages.ServerMessageReceiver),
) (err error) {
	return o.Channel.SubscribeServerMessage(ctx, cb)
}
