// Code generated by go-asyncapi tool. DO NOT EDIT.

package operations

import (
	"context"
	"github.com/bdragon300/go-asyncapi/run"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/channels"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/messages"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
)

type RequestAuthenticationServerWs interface {
	OpenAuthWs(context.Context, run.AnySecurityScheme) (*channels.AuthWs, error)
	OpenRequestAuthenticationWs(context.Context) (*RequestAuthenticationWs, error)
	Producer() ws.Producer
	Consumer() ws.Consumer
}

func OpenRequestAuthenticationWs(
	ctx context.Context,
	server RequestAuthenticationServerWs,

) (*RequestAuthenticationWs, error) {
	ch, err := channels.OpenAuthWs(
		ctx,
		server,

		nil,
		nil,
	)
	if err != nil {
		return nil, err
	}

	return &RequestAuthenticationWs{
		Channel: ch,
	}, nil
}

type RequestAuthenticationChannelWs interface {
	Close() error

	SealClientMessage(ws.EnvelopeWriter, channels.AuthEnvelopeMarshalerWs) error
	PublishClientMessage(context.Context, channels.AuthEnvelopeMarshalerWs) error

	UnsealClientMessage(ws.EnvelopeReader, channels.AuthEnvelopeUnmarshalerWs) error
	SubscribeClientMessage(context.Context, func(messages.ClientMessageReceiver)) error
}

type RequestAuthenticationWs struct {
	Channel RequestAuthenticationChannelWs
}

func (c RequestAuthenticationWs) Close() error {
	return c.Channel.Close()
}

func (o RequestAuthenticationWs) SealClientMessage(
	envelope ws.EnvelopeWriter,
	message channels.AuthEnvelopeMarshalerWs,
) error {
	return o.Channel.SealClientMessage(envelope, message)
}

func (o RequestAuthenticationWs) PublishClientMessage(
	ctx context.Context,

	message channels.AuthEnvelopeMarshalerWs,
) error {
	return o.Channel.PublishClientMessage(ctx, message)
}
