// Code generated by go-asyncapi tool. DO NOT EDIT.

package operations

import (
	"context"
	"github.com/bdragon300/go-asyncapi/run"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/channels"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/messages"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
)

type SubscribeActivityServerWs interface {
	OpenEventsWs(context.Context, run.AnySecurityScheme) (*channels.EventsWs, error)
	OpenSubscribeActivityWs(context.Context, SubscribeActivitySecurity) (*SubscribeActivityWs, error)
	Producer() ws.Producer
	Consumer() ws.Consumer
}

type SubscribeActivitySecurity interface {
	run.AnySecurityScheme
	SubscribeActivitySecurity()
}

func OpenSubscribeActivityWs(
	ctx context.Context,
	server SubscribeActivityServerWs,

	security SubscribeActivitySecurity,
) (*SubscribeActivityWs, error) {
	ch, err := channels.OpenEventsWs(
		ctx,
		server,

		nil,
		security,
	)
	if err != nil {
		return nil, err
	}

	return &SubscribeActivityWs{
		Channel: ch,
	}, nil
}

type SubscribeActivityChannelWs interface {
	Close() error

	SealClientMessage(ws.EnvelopeWriter, channels.EventsEnvelopeMarshalerWs) error
	PublishClientMessage(context.Context, channels.EventsEnvelopeMarshalerWs) error

	UnsealClientMessage(ws.EnvelopeReader, channels.EventsEnvelopeUnmarshalerWs) error
	SubscribeClientMessage(context.Context, func(messages.ClientMessageReceiver)) error
}

type SubscribeActivityWs struct {
	Channel SubscribeActivityChannelWs
}

func (c SubscribeActivityWs) Close() error {
	return c.Channel.Close()
}

func (o SubscribeActivityWs) SealClientMessage(
	envelope ws.EnvelopeWriter,
	message channels.EventsEnvelopeMarshalerWs,
) error {
	return o.Channel.SealClientMessage(envelope, message)
}

func (o SubscribeActivityWs) PublishClientMessage(
	ctx context.Context,

	message channels.EventsEnvelopeMarshalerWs,
) error {
	return o.Channel.PublishClientMessage(ctx, message)
}
