// Code generated by go-asyncapi tool. DO NOT EDIT.

package channels

import (
	"context"
	"errors"
	"fmt"
	"github.com/bdragon300/go-asyncapi/run"
	ws2 "github.com/gobwas/ws"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/messages"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
)

func AuthAddress() run.ParamString {
	return run.ParamString{
		Expr: "/api/auth-events",
	}
}

func NewAuthWs(

	publisher ws.Publisher,
	subscriber ws.Subscriber,
) *AuthWs {
	res := AuthWs{
		address: AuthAddress(), publisher: publisher, subscriber: subscriber,
	}
	return &res
}

type AuthServerWs interface {
	OpenAuthWs(context.Context, run.AnySecurityScheme) (*AuthWs, error)
	Producer() ws.Producer
	Consumer() ws.Consumer
}

func OpenAuthWs(
	ctx context.Context,
	server AuthServerWs,

	opBindings *ws.OperationBindings,
	security run.AnySecurityScheme,
) (*AuthWs, error) {
	var err error
	address, err := AuthAddress().Expand()
	if err != nil {
		return nil, err
	}
	var publisher ws.Publisher
	producer := server.Producer()
	if producer != nil {
		publisher, err = producer.Publisher(
			ctx,
			address,
			nil,
			opBindings,
			security,
		)
		if err != nil {
			return nil, err
		}
	}
	var subscriber ws.Subscriber
	consumer := server.Consumer()
	if consumer != nil {
		subscriber, err = consumer.Subscriber(
			ctx,
			address,
			nil,
			opBindings,
			security,
		)
		if err != nil {
			return nil, err
		}
	}

	return NewAuthWs(

		publisher,
		subscriber,
	), nil
}

type AuthWs struct {
	address    run.ParamString
	publisher  ws.Publisher
	subscriber ws.Subscriber
}

func (c AuthWs) Address() run.ParamString {
	return c.address
}

func (c AuthWs) Close() (err error) {
	if c.publisher != nil {
		err = errors.Join(err, c.publisher.Close())
	}
	if c.subscriber != nil {
		err = errors.Join(err, c.subscriber.Close())
	}
	return
}

type AuthEnvelopeMarshalerWs interface {
	MarshalAuthWs(envelope ws.EnvelopeWriter) error
}

func (c AuthWs) SealRequest(
	envelope ws.EnvelopeWriter,
	message AuthEnvelopeMarshalerWs,
) error {
	if err := message.MarshalAuthWs(envelope); err != nil {
		return err
	}

	return nil
}

func (c AuthWs) PublishRequest(
	ctx context.Context,

	message AuthEnvelopeMarshalerWs,
) error {
	envelope := ws.NewEnvelopeOut(nil)
	if err := c.SealRequest(envelope, message); err != nil {
		return err
	}

	envelope.SetOpCode(byte(ws2.OpBinary))
	return c.Publish(ctx, envelope)
}
func (c AuthWs) SealResponse(
	envelope ws.EnvelopeWriter,
	message AuthEnvelopeMarshalerWs,
) error {
	if err := message.MarshalAuthWs(envelope); err != nil {
		return err
	}

	return nil
}

func (c AuthWs) PublishResponse(
	ctx context.Context,

	message AuthEnvelopeMarshalerWs,
) error {
	envelope := ws.NewEnvelopeOut(nil)
	if err := c.SealResponse(envelope, message); err != nil {
		return err
	}

	envelope.SetOpCode(byte(ws2.OpBinary))
	return c.Publish(ctx, envelope)
}

func (c AuthWs) Publisher() ws.Publisher {
	return c.publisher
}

func (c AuthWs) Publish(ctx context.Context, envelopes ...ws.EnvelopeWriter) error {
	return c.publisher.Send(ctx, envelopes...)
}

type AuthEnvelopeUnmarshalerWs interface {
	UnmarshalAuthWs(envelope ws.EnvelopeReader) error
}

func (c AuthWs) UnsealRequest(
	envelope ws.EnvelopeReader,
	message AuthEnvelopeUnmarshalerWs,
) error {
	return message.UnmarshalAuthWs(envelope)
}

func (c AuthWs) SubscribeRequest(
	ctx context.Context,
	cb func(message messages.RequestReceiver),
) (err error) {
	subCtx, cancel := context.WithCancel(ctx)
	defer cancel()

	subErr := c.Subscribe(subCtx, func(envelope ws.EnvelopeReader) {
		message := new(messages.RequestIn)
		if err2 := c.UnsealRequest(envelope, message); err2 != nil {
			err = fmt.Errorf("%w: %w", run.ErrUnsealEnvelope, err2)
			cancel()
			return
		}
		cb(message)
	})
	if err != nil {
		return err
	}
	return subErr
}
func (c AuthWs) UnsealResponse(
	envelope ws.EnvelopeReader,
	message AuthEnvelopeUnmarshalerWs,
) error {
	return message.UnmarshalAuthWs(envelope)
}

func (c AuthWs) SubscribeResponse(
	ctx context.Context,
	cb func(message messages.ResponseReceiver),
) (err error) {
	subCtx, cancel := context.WithCancel(ctx)
	defer cancel()

	subErr := c.Subscribe(subCtx, func(envelope ws.EnvelopeReader) {
		message := new(messages.ResponseIn)
		if err2 := c.UnsealResponse(envelope, message); err2 != nil {
			err = fmt.Errorf("%w: %w", run.ErrUnsealEnvelope, err2)
			cancel()
			return
		}
		cb(message)
	})
	if err != nil {
		return err
	}
	return subErr
}

func (c AuthWs) Subscriber() ws.Subscriber {
	return c.subscriber
}

func (c AuthWs) Subscribe(ctx context.Context, cb func(envelope ws.EnvelopeReader)) error {
	return c.subscriber.Receive(ctx, cb)
}
