// Code generated by go-asyncapi tool. DO NOT EDIT.

package channels

import (
	"context"
	"errors"
	"fmt"
	"github.com/bdragon300/go-asyncapi/run"
	ws2 "github.com/gobwas/ws"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/messages"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
)

func EventsAddress() run.ParamString {
	return run.ParamString{
		Expr: "/api/events",
	}
}

func NewEventsWs(

	publisher ws.Publisher,
	subscriber ws.Subscriber,
) *EventsWs {
	res := EventsWs{
		address: EventsAddress(), publisher: publisher, subscriber: subscriber,
	}
	return &res
}

type EventsServerWs interface {
	OpenEventsWs(context.Context, run.AnySecurityScheme) (*EventsWs, error)
	Producer() ws.Producer
	Consumer() ws.Consumer
}

func OpenEventsWs(
	ctx context.Context,
	server EventsServerWs,

	opBindings *ws.OperationBindings,
	security run.AnySecurityScheme,
) (*EventsWs, error) {
	var err error
	address, err := EventsAddress().Expand()
	if err != nil {
		return nil, err
	}
	var publisher ws.Publisher
	producer := server.Producer()
	if producer != nil {
		publisher, err = producer.Publisher(
			ctx,
			address,
			nil,
			opBindings,
			security,
		)
		if err != nil {
			return nil, err
		}
	}
	var subscriber ws.Subscriber
	consumer := server.Consumer()
	if consumer != nil {
		subscriber, err = consumer.Subscriber(
			ctx,
			address,
			nil,
			opBindings,
			security,
		)
		if err != nil {
			return nil, err
		}
	}

	return NewEventsWs(

		publisher,
		subscriber,
	), nil
}

type EventsWs struct {
	address    run.ParamString
	publisher  ws.Publisher
	subscriber ws.Subscriber
}

func (c EventsWs) Address() run.ParamString {
	return c.address
}

func (c EventsWs) Close() (err error) {
	if c.publisher != nil {
		err = errors.Join(err, c.publisher.Close())
	}
	if c.subscriber != nil {
		err = errors.Join(err, c.subscriber.Close())
	}
	return
}

type EventsEnvelopeMarshalerWs interface {
	MarshalEventsWs(envelope ws.EnvelopeWriter) error
}

func (c EventsWs) SealSubscribe(
	envelope ws.EnvelopeWriter,
	message EventsEnvelopeMarshalerWs,
) error {
	if err := message.MarshalEventsWs(envelope); err != nil {
		return err
	}

	return nil
}

func (c EventsWs) PublishSubscribe(
	ctx context.Context,

	message EventsEnvelopeMarshalerWs,
) error {
	envelope := ws.NewEnvelopeOut(nil)
	if err := c.SealSubscribe(envelope, message); err != nil {
		return err
	}

	envelope.SetOpCode(byte(ws2.OpBinary))
	return c.Publish(ctx, envelope)
}
func (c EventsWs) SealActivity(
	envelope ws.EnvelopeWriter,
	message EventsEnvelopeMarshalerWs,
) error {
	if err := message.MarshalEventsWs(envelope); err != nil {
		return err
	}

	return nil
}

func (c EventsWs) PublishActivity(
	ctx context.Context,

	message EventsEnvelopeMarshalerWs,
) error {
	envelope := ws.NewEnvelopeOut(nil)
	if err := c.SealActivity(envelope, message); err != nil {
		return err
	}

	envelope.SetOpCode(byte(ws2.OpBinary))
	return c.Publish(ctx, envelope)
}

func (c EventsWs) Publisher() ws.Publisher {
	return c.publisher
}

func (c EventsWs) Publish(ctx context.Context, envelopes ...ws.EnvelopeWriter) error {
	return c.publisher.Send(ctx, envelopes...)
}

type EventsEnvelopeUnmarshalerWs interface {
	UnmarshalEventsWs(envelope ws.EnvelopeReader) error
}

func (c EventsWs) UnsealSubscribe(
	envelope ws.EnvelopeReader,
	message EventsEnvelopeUnmarshalerWs,
) error {
	return message.UnmarshalEventsWs(envelope)
}

func (c EventsWs) SubscribeSubscribe(
	ctx context.Context,
	cb func(message messages.SubscribeReceiver),
) (err error) {
	subCtx, cancel := context.WithCancel(ctx)
	defer cancel()

	subErr := c.Subscribe(subCtx, func(envelope ws.EnvelopeReader) {
		message := new(messages.SubscribeIn)
		if err2 := c.UnsealSubscribe(envelope, message); err2 != nil {
			err = fmt.Errorf("%w: %w", run.ErrUnsealEnvelope, err2)
			cancel()
			return
		}
		cb(message)
	})
	if err != nil {
		return err
	}
	return subErr
}
func (c EventsWs) UnsealActivity(
	envelope ws.EnvelopeReader,
	message EventsEnvelopeUnmarshalerWs,
) error {
	return message.UnmarshalEventsWs(envelope)
}

func (c EventsWs) SubscribeActivity(
	ctx context.Context,
	cb func(message messages.ActivityReceiver),
) (err error) {
	subCtx, cancel := context.WithCancel(ctx)
	defer cancel()

	subErr := c.Subscribe(subCtx, func(envelope ws.EnvelopeReader) {
		message := new(messages.ActivityIn)
		if err2 := c.UnsealActivity(envelope, message); err2 != nil {
			err = fmt.Errorf("%w: %w", run.ErrUnsealEnvelope, err2)
			cancel()
			return
		}
		cb(message)
	})
	if err != nil {
		return err
	}
	return subErr
}

func (c EventsWs) Subscriber() ws.Subscriber {
	return c.subscriber
}

func (c EventsWs) Subscribe(ctx context.Context, cb func(envelope ws.EnvelopeReader)) error {
	return c.subscriber.Receive(ctx, cb)
}
