// Code generated by go-asyncapi tool. DO NOT EDIT.

package messages

import (
	"encoding/json"
	"github.com/bdragon300/go-asyncapi/run"
	"github.com/google/uuid"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/schemas"
	"io"
)

type ResponseSender interface {
	SetPayload(payload struct {
		// ID--Correlation ID from the originating request.
		ID *uuid.UUID `json:"id"`
		/*
		Type--0 - ActivityData: user activity snapshot
		1 - AuthenticationURL: one-time authentication URL
		2 - Authentication: session token
		*/
		Type *int `json:"type"`
		// Data--Payload varies by type.
		Data *struct {
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf0
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf1
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf2
		} `json:"data"`
	}) *ResponseOut
	SetHeaders(headers map[string]any) *ResponseOut
}

// ResponseOut-- (Outbound Message)
type ResponseOut struct {
	Payload struct {
		// ID--Correlation ID from the originating request.
		ID *uuid.UUID `json:"id"`
		/*
		Type--0 - ActivityData: user activity snapshot
		1 - AuthenticationURL: one-time authentication URL
		2 - Authentication: session token
		*/
		Type *int `json:"type"`
		// Data--Payload varies by type.
		Data *struct {
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf0
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf1
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf2
		} `json:"data"`
	}
	Headers map[string]any
}

func (m *ResponseOut) SetPayload(payload struct {
	// ID--Correlation ID from the originating request.
	ID *uuid.UUID `json:"id"`
	/*
	Type--0 - ActivityData: user activity snapshot
	1 - AuthenticationURL: one-time authentication URL
	2 - Authentication: session token
	*/
	Type *int `json:"type"`
	// Data--Payload varies by type.
	Data *struct {
		*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf0
		*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf1
		*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf2
	} `json:"data"`
}) *ResponseOut {
	m.Payload = payload
	return m
}

func (m *ResponseOut) SetHeaders(headers map[string]any) *ResponseOut {
	m.Headers = headers
	return m
}

type ResponseReceiver interface {
	Payload() struct {
		// ID--Correlation ID from the originating request.
		ID *uuid.UUID `json:"id"`
		/*
		Type--0 - ActivityData: user activity snapshot
		1 - AuthenticationURL: one-time authentication URL
		2 - Authentication: session token
		*/
		Type *int `json:"type"`
		// Data--Payload varies by type.
		Data *struct {
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf0
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf1
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf2
		} `json:"data"`
	}
	Headers() map[string]any
}

// ResponseIn-- (Inbound Message)
type ResponseIn struct {
	payload struct {
		// ID--Correlation ID from the originating request.
		ID *uuid.UUID `json:"id"`
		/*
		Type--0 - ActivityData: user activity snapshot
		1 - AuthenticationURL: one-time authentication URL
		2 - Authentication: session token
		*/
		Type *int `json:"type"`
		// Data--Payload varies by type.
		Data *struct {
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf0
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf1
			*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf2
		} `json:"data"`
	}
	headers map[string]any
}

func (m *ResponseIn) Payload() struct {
	// ID--Correlation ID from the originating request.
	ID *uuid.UUID `json:"id"`
	/*
	Type--0 - ActivityData: user activity snapshot
	1 - AuthenticationURL: one-time authentication URL
	2 - Authentication: session token
	*/
	Type *int `json:"type"`
	// Data--Payload varies by type.
	Data *struct {
		*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf0
		*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf1
		*schemas.ChannelsAuthMessagesResponsePayloadPropertiesDataOneOf2
	} `json:"data"`
} {
	return m.payload
}

func (m *ResponseIn) Headers() map[string]any {
	return m.headers
}

func (m *ResponseOut) MarshalAuthWs(envelope ws.EnvelopeWriter) error {
	return m.MarshalEnvelopeWs(envelope)
}

func (m *ResponseOut) MarshalEnvelopeWs(envelope ws.EnvelopeWriter) error {
	if err := m.MarshalWs(envelope); err != nil {
		return err
	}
	envelope.SetContentType("application/json")
	envelope.SetHeaders(run.Headers(m.Headers))
	return nil
}

func (m *ResponseOut) MarshalWs(w io.Writer) error {
	// MIME type: application/json

	// Default encoder
	enc := json.NewEncoder(w)
	if err := enc.Encode(m.Payload); err != nil {
		return err
	}
	return nil
}

func (m *ResponseIn) UnmarshalAuthWs(envelope ws.EnvelopeReader) error {
	return m.UnmarshalEnvelopeWs(envelope)
}

func (m *ResponseIn) UnmarshalEnvelopeWs(envelope ws.EnvelopeReader) error {
	if err := m.UnmarshalWs(envelope); err != nil {
		return err
	}
	m.headers = map[string]any(envelope.Headers())
	return nil
}

func (m *ResponseIn) UnmarshalWs(r io.Reader) error {
	// MIME type: application/json

	// Default decoder
	dec := json.NewDecoder(r)
	if err := dec.Decode(&m.payload); err != nil {
		return err
	}
	return nil
}
