// Code generated by go-asyncapi tool. DO NOT EDIT.

package messages

import (
	"encoding/json"
	"github.com/bdragon300/go-asyncapi/run"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/schemas"
	"io"
)

type ServerMessageSender interface {
	SetPayload(payload schemas.ServerMessageStruct) *ServerMessageOut
	SetHeaders(headers map[string]any) *ServerMessageOut
}

// ServerMessageOut-- (Outbound Message)
type ServerMessageOut struct {
	Payload schemas.ServerMessageStruct
	Headers map[string]any
}

func (m *ServerMessageOut) SetPayload(payload schemas.ServerMessageStruct) *ServerMessageOut {
	m.Payload = payload
	return m
}

func (m *ServerMessageOut) SetHeaders(headers map[string]any) *ServerMessageOut {
	m.Headers = headers
	return m
}

type ServerMessageReceiver interface {
	Payload() schemas.ServerMessageStruct
	Headers() map[string]any
}

// ServerMessageIn-- (Inbound Message)
type ServerMessageIn struct {
	payload schemas.ServerMessageStruct
	headers map[string]any
}

func (m *ServerMessageIn) Payload() schemas.ServerMessageStruct {
	return m.payload
}

func (m *ServerMessageIn) Headers() map[string]any {
	return m.headers
}

func (m *ServerMessageOut) MarshalAuthWs(envelope ws.EnvelopeWriter) error {
	return m.MarshalEnvelopeWs(envelope)
}
func (m *ServerMessageOut) MarshalEventsWs(envelope ws.EnvelopeWriter) error {
	return m.MarshalEnvelopeWs(envelope)
}

func (m *ServerMessageOut) MarshalEnvelopeWs(envelope ws.EnvelopeWriter) error {
	if err := m.MarshalWs(envelope); err != nil {
		return err
	}
	envelope.SetContentType("application/json")
	envelope.SetHeaders(run.Headers(m.Headers))
	return nil
}

func (m *ServerMessageOut) MarshalWs(w io.Writer) error {
	// MIME type: application/json

	// Default encoder
	enc := json.NewEncoder(w)
	if err := enc.Encode(m.Payload); err != nil {
		return err
	}
	return nil
}

func (m *ServerMessageIn) UnmarshalAuthWs(envelope ws.EnvelopeReader) error {
	return m.UnmarshalEnvelopeWs(envelope)
}
func (m *ServerMessageIn) UnmarshalEventsWs(envelope ws.EnvelopeReader) error {
	return m.UnmarshalEnvelopeWs(envelope)
}

func (m *ServerMessageIn) UnmarshalEnvelopeWs(envelope ws.EnvelopeReader) error {
	if err := m.UnmarshalWs(envelope); err != nil {
		return err
	}
	m.headers = map[string]any(envelope.Headers())
	return nil
}

func (m *ServerMessageIn) UnmarshalWs(r io.Reader) error {
	// MIME type: application/json

	// Default decoder
	dec := json.NewDecoder(r)
	if err := dec.Decode(&m.payload); err != nil {
		return err
	}
	return nil
}
