// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

import (
	"github.com/google/uuid"
	"time"
)

type Activity struct {
	// SessionID--Unique identifier for this listening session.
	SessionID *string `json:"session_id"`
	// TrackID--Track ID.
	TrackID *uuid.UUID `json:"track_id"`
	// TrackName--Track title.
	TrackName *string `json:"track_name"`
	// Artists--Credited track artists.
	Artists *[]Artist `json:"artists"`
	// AlbumName--Album name.
	AlbumName string `json:"album_name"`
	// AlbumAssetURL--Album cover URL.
	AlbumAssetURL string `json:"album_asset_url"`
	// Active--Whether the user is currently playing this track (true) or has stopped/paused (false)..
	Active *bool `json:"active"`
	// Position--Current playback position in seconds.
	Position *int64 `json:"position"`
	// StartTimestamp--When the track was played.
	StartTimestamp *time.Time `json:"start_timestamp"`
	// EndTimestamp--Projected end time based on track duration.
	EndTimestamp *time.Time `json:"end_timestamp"`
	// UpdatedAt--When this activity was last updated.
	UpdatedAt *time.Time `json:"updated_at"`
}
