// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

type ChannelsEventsMessagesActivityPayloadPropertiesDataOneOf2 struct {
	// Token--JWT authentication token.
	Token *string `json:"token"`
}
