// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

import (
	"github.com/google/uuid"
)

type ServerMessageStruct struct {
	// ID--Correlation ID from the originating request.
	ID   *uuid.UUID       `json:"id"`
	Type *ServerEventType `json:"type"`
	// Data--Payload varies by type.
	Data *struct {
		*ActivityData
		*AuthURL
		*AuthToken
	} `json:"data"`
}
