// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

/*
ServerEventType--0 - ActivityData: user activity snapshot
1 - AuthenticationURL: one-time authentication URL
2 - Authentication: session token
*/
type ServerEventType int
