// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

import (
	"github.com/google/uuid"
)

type ServerMessageStruct struct {
	// ID--Correlation ID from the originating request.
	ID *uuid.UUID `json:"id"`
	/*
	Type--0 - ActivityData: user activity snapshot
	1 - AuthenticationURL: one-time authentication URL
	2 - Authentication: session token
	*/
	Type *int `json:"type"`
	// Data--Payload varies by type.
	Data *struct {
		*ComponentsSchemasServerMessageStructPropertiesDataOneOf0
		*ComponentsSchemasServerMessageStructPropertiesDataOneOf1
		*ComponentsSchemasServerMessageStructPropertiesDataOneOf2
	} `json:"data"`
}
