// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

import (
	"github.com/google/uuid"
)

type Subscription struct {
	// Users--User UUIDs to subscribe to.
	Users *[]uuid.UUID `json:"users"`
}
