// Code generated by go-asyncapi tool. DO NOT EDIT.

package servers

import (
	"context"
	"errors"
	"github.com/bdragon300/go-asyncapi/run"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/channels"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/operations"
	"gitlab.com/AlexJarrah/echoes-api/bindings/go/asyncapi/proto/ws"
	"io"
	"net/url"
)

func ProductionURL() (*url.URL, error) {
	return &url.URL{Scheme: "ws", Host: "echoes.la", Path: ""}, nil
}

func NewProduction(producer ws.Producer, consumer ws.Consumer) *Production {
	return &Production{
		producer: producer,
		consumer: consumer,
	}
}

type ProductionClosable struct {
	Production
}

func (c ProductionClosable) Close() error {
	var err error
	if v, ok := any(c.producer).(io.Closer); ok {
		err = errors.Join(err, v.Close())
	}
	if v, ok := any(c.consumer).(io.Closer); ok {
		err = errors.Join(err, v.Close())
	}
	return err
}

func ConnectProductionBidi(
	ctx context.Context,
	url *url.URL,

) (*ProductionClosable, error) {
	var bindings *ws.ServerBindings
	producer := ws.NewProducer(url, bindings, nil)
	consumer := ws.NewConsumer(bindings, nil)
	return &ProductionClosable{
		Production{producer: producer, consumer: consumer},
	}, nil
}

func ConnectProductionProducer(
	ctx context.Context,
	url *url.URL,

) (*ProductionClosable, error) {
	var bindings *ws.ServerBindings
	producer := ws.NewProducer(url, bindings, nil)
	return &ProductionClosable{
		Production{producer: producer},
	}, nil
}

func ConnectProductionConsumer(
	ctx context.Context,
	url *url.URL,

) (*ProductionClosable, error) {
	var bindings *ws.ServerBindings
	consumer := ws.NewConsumer(bindings, nil)
	return &ProductionClosable{
		Production{consumer: consumer},
	}, nil
}

type Production struct {
	producer ws.Producer
	consumer ws.Consumer
}

func (s Production) Name() string {
	return "Production"
}

func (s Production) Producer() ws.Producer {
	return s.producer
}

func (s Production) Consumer() ws.Consumer {
	return s.consumer
}

func (s Production) OpenEventsWs(
	ctx context.Context,

	security run.AnySecurityScheme,
) (*channels.EventsWs, error) {
	return channels.OpenEventsWs(
		ctx, s, nil, security,
	)
}
func (s Production) OpenAuthWs(
	ctx context.Context,

	security run.AnySecurityScheme,
) (*channels.AuthWs, error) {
	return channels.OpenAuthWs(
		ctx, s, nil, security,
	)
}

func (s Production) OpenReceiveActivityWs(
	ctx context.Context,

	security operations.ReceiveActivitySecurity,
) (*operations.ReceiveActivityWs, error) {
	return operations.OpenReceiveActivityWs(
		ctx, s, security,
	)
}
func (s Production) OpenSubscribeActivityWs(
	ctx context.Context,

	security operations.SubscribeActivitySecurity,
) (*operations.SubscribeActivityWs, error) {
	return operations.OpenSubscribeActivityWs(
		ctx, s, security,
	)
}
func (s Production) OpenReceiveAuthResponseWs(
	ctx context.Context,

) (*operations.ReceiveAuthResponseWs, error) {
	return operations.OpenReceiveAuthResponseWs(
		ctx, s,
	)
}
func (s Production) OpenRequestAuthenticationWs(
	ctx context.Context,

) (*operations.RequestAuthenticationWs, error) {
	return operations.OpenRequestAuthenticationWs(
		ctx, s,
	)
}
