// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"io"
	"time"

	"github.com/google/uuid"
)

type AddFriendApplicationJSONBadRequest ErrorResponse

func (*AddFriendApplicationJSONBadRequest) addFriendRes() {}

type AddFriendApplicationJSONForbidden ErrorResponse

func (*AddFriendApplicationJSONForbidden) addFriendRes() {}

type AddFriendApplicationJSONInternalServerError ErrorResponse

func (*AddFriendApplicationJSONInternalServerError) addFriendRes() {}

type AddFriendApplicationJSONNotFound ErrorResponse

func (*AddFriendApplicationJSONNotFound) addFriendRes() {}

type AddFriendApplicationJSONUnauthorized ErrorResponse

func (*AddFriendApplicationJSONUnauthorized) addFriendRes() {}

type AddToLibraryApplicationJSONBadRequest ErrorResponse

func (*AddToLibraryApplicationJSONBadRequest) addToLibraryRes() {}

type AddToLibraryApplicationJSONInternalServerError ErrorResponse

func (*AddToLibraryApplicationJSONInternalServerError) addToLibraryRes() {}

type AddToLibraryApplicationJSONUnauthorized ErrorResponse

func (*AddToLibraryApplicationJSONUnauthorized) addToLibraryRes() {}

// Ref: #/components/schemas/Album
type Album struct {
	AlbumID         uuid.UUID      `json:"album_id"`
	UserID          OptNilUUID     `json:"user_id"`
	BaseAlbumID     OptNilUUID     `json:"base_album_id"`
	Name            string         `json:"name"`
	ReleaseDate     OptNilDateTime `json:"release_date"`
	MusicbrainzID   OptNilUUID     `json:"musicbrainz_id"`
	ImageIds        OptNilString   `json:"image_ids"`
	SpotifyURL      OptNilString   `json:"spotify_url"`
	AppleMusicURL   OptNilString   `json:"apple_music_url"`
	TidalURL        OptNilString   `json:"tidal_url"`
	YoutubeMusicURL OptNilString   `json:"youtube_music_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       OptNilDateTime `json:"updated_at"`
}

// GetAlbumID returns the value of AlbumID.
func (s *Album) GetAlbumID() uuid.UUID {
	return s.AlbumID
}

// GetUserID returns the value of UserID.
func (s *Album) GetUserID() OptNilUUID {
	return s.UserID
}

// GetBaseAlbumID returns the value of BaseAlbumID.
func (s *Album) GetBaseAlbumID() OptNilUUID {
	return s.BaseAlbumID
}

// GetName returns the value of Name.
func (s *Album) GetName() string {
	return s.Name
}

// GetReleaseDate returns the value of ReleaseDate.
func (s *Album) GetReleaseDate() OptNilDateTime {
	return s.ReleaseDate
}

// GetMusicbrainzID returns the value of MusicbrainzID.
func (s *Album) GetMusicbrainzID() OptNilUUID {
	return s.MusicbrainzID
}

// GetImageIds returns the value of ImageIds.
func (s *Album) GetImageIds() OptNilString {
	return s.ImageIds
}

// GetSpotifyURL returns the value of SpotifyURL.
func (s *Album) GetSpotifyURL() OptNilString {
	return s.SpotifyURL
}

// GetAppleMusicURL returns the value of AppleMusicURL.
func (s *Album) GetAppleMusicURL() OptNilString {
	return s.AppleMusicURL
}

// GetTidalURL returns the value of TidalURL.
func (s *Album) GetTidalURL() OptNilString {
	return s.TidalURL
}

// GetYoutubeMusicURL returns the value of YoutubeMusicURL.
func (s *Album) GetYoutubeMusicURL() OptNilString {
	return s.YoutubeMusicURL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Album) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Album) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetAlbumID sets the value of AlbumID.
func (s *Album) SetAlbumID(val uuid.UUID) {
	s.AlbumID = val
}

// SetUserID sets the value of UserID.
func (s *Album) SetUserID(val OptNilUUID) {
	s.UserID = val
}

// SetBaseAlbumID sets the value of BaseAlbumID.
func (s *Album) SetBaseAlbumID(val OptNilUUID) {
	s.BaseAlbumID = val
}

// SetName sets the value of Name.
func (s *Album) SetName(val string) {
	s.Name = val
}

// SetReleaseDate sets the value of ReleaseDate.
func (s *Album) SetReleaseDate(val OptNilDateTime) {
	s.ReleaseDate = val
}

// SetMusicbrainzID sets the value of MusicbrainzID.
func (s *Album) SetMusicbrainzID(val OptNilUUID) {
	s.MusicbrainzID = val
}

// SetImageIds sets the value of ImageIds.
func (s *Album) SetImageIds(val OptNilString) {
	s.ImageIds = val
}

// SetSpotifyURL sets the value of SpotifyURL.
func (s *Album) SetSpotifyURL(val OptNilString) {
	s.SpotifyURL = val
}

// SetAppleMusicURL sets the value of AppleMusicURL.
func (s *Album) SetAppleMusicURL(val OptNilString) {
	s.AppleMusicURL = val
}

// SetTidalURL sets the value of TidalURL.
func (s *Album) SetTidalURL(val OptNilString) {
	s.TidalURL = val
}

// SetYoutubeMusicURL sets the value of YoutubeMusicURL.
func (s *Album) SetYoutubeMusicURL(val OptNilString) {
	s.YoutubeMusicURL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Album) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Album) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

func (*Album) getAlbumRes() {}

// Ref: #/components/schemas/AlbumArtist
type AlbumArtist struct {
	AlbumID  uuid.UUID `json:"album_id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

// GetAlbumID returns the value of AlbumID.
func (s *AlbumArtist) GetAlbumID() uuid.UUID {
	return s.AlbumID
}

// GetArtistID returns the value of ArtistID.
func (s *AlbumArtist) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// SetAlbumID sets the value of AlbumID.
func (s *AlbumArtist) SetAlbumID(val uuid.UUID) {
	s.AlbumID = val
}

// SetArtistID sets the value of ArtistID.
func (s *AlbumArtist) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

// Ref: #/components/schemas/AlbumTrack
type AlbumTrack struct {
	AlbumID     uuid.UUID  `json:"album_id"`
	TrackID     uuid.UUID  `json:"track_id"`
	DiscNumber  OptNilInt8 `json:"disc_number"`
	TrackNumber OptNilInt8 `json:"track_number"`
}

// GetAlbumID returns the value of AlbumID.
func (s *AlbumTrack) GetAlbumID() uuid.UUID {
	return s.AlbumID
}

// GetTrackID returns the value of TrackID.
func (s *AlbumTrack) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetDiscNumber returns the value of DiscNumber.
func (s *AlbumTrack) GetDiscNumber() OptNilInt8 {
	return s.DiscNumber
}

// GetTrackNumber returns the value of TrackNumber.
func (s *AlbumTrack) GetTrackNumber() OptNilInt8 {
	return s.TrackNumber
}

// SetAlbumID sets the value of AlbumID.
func (s *AlbumTrack) SetAlbumID(val uuid.UUID) {
	s.AlbumID = val
}

// SetTrackID sets the value of TrackID.
func (s *AlbumTrack) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetDiscNumber sets the value of DiscNumber.
func (s *AlbumTrack) SetDiscNumber(val OptNilInt8) {
	s.DiscNumber = val
}

// SetTrackNumber sets the value of TrackNumber.
func (s *AlbumTrack) SetTrackNumber(val OptNilInt8) {
	s.TrackNumber = val
}

// Ref: #/components/schemas/Artist
type Artist struct {
	ArtistID        uuid.UUID      `json:"artist_id"`
	UserID          OptNilUUID     `json:"user_id"`
	Name            string         `json:"name"`
	Bio             OptNilString   `json:"bio"`
	ImageIds        OptNilString   `json:"image_ids"`
	MusicbrainzID   OptNilUUID     `json:"musicbrainz_id"`
	SpotifyURL      OptNilString   `json:"spotify_url"`
	AppleMusicURL   OptNilString   `json:"apple_music_url"`
	TidalURL        OptNilString   `json:"tidal_url"`
	YoutubeMusicURL OptNilString   `json:"youtube_music_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       OptNilDateTime `json:"updated_at"`
}

// GetArtistID returns the value of ArtistID.
func (s *Artist) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// GetUserID returns the value of UserID.
func (s *Artist) GetUserID() OptNilUUID {
	return s.UserID
}

// GetName returns the value of Name.
func (s *Artist) GetName() string {
	return s.Name
}

// GetBio returns the value of Bio.
func (s *Artist) GetBio() OptNilString {
	return s.Bio
}

// GetImageIds returns the value of ImageIds.
func (s *Artist) GetImageIds() OptNilString {
	return s.ImageIds
}

// GetMusicbrainzID returns the value of MusicbrainzID.
func (s *Artist) GetMusicbrainzID() OptNilUUID {
	return s.MusicbrainzID
}

// GetSpotifyURL returns the value of SpotifyURL.
func (s *Artist) GetSpotifyURL() OptNilString {
	return s.SpotifyURL
}

// GetAppleMusicURL returns the value of AppleMusicURL.
func (s *Artist) GetAppleMusicURL() OptNilString {
	return s.AppleMusicURL
}

// GetTidalURL returns the value of TidalURL.
func (s *Artist) GetTidalURL() OptNilString {
	return s.TidalURL
}

// GetYoutubeMusicURL returns the value of YoutubeMusicURL.
func (s *Artist) GetYoutubeMusicURL() OptNilString {
	return s.YoutubeMusicURL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Artist) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Artist) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetArtistID sets the value of ArtistID.
func (s *Artist) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

// SetUserID sets the value of UserID.
func (s *Artist) SetUserID(val OptNilUUID) {
	s.UserID = val
}

// SetName sets the value of Name.
func (s *Artist) SetName(val string) {
	s.Name = val
}

// SetBio sets the value of Bio.
func (s *Artist) SetBio(val OptNilString) {
	s.Bio = val
}

// SetImageIds sets the value of ImageIds.
func (s *Artist) SetImageIds(val OptNilString) {
	s.ImageIds = val
}

// SetMusicbrainzID sets the value of MusicbrainzID.
func (s *Artist) SetMusicbrainzID(val OptNilUUID) {
	s.MusicbrainzID = val
}

// SetSpotifyURL sets the value of SpotifyURL.
func (s *Artist) SetSpotifyURL(val OptNilString) {
	s.SpotifyURL = val
}

// SetAppleMusicURL sets the value of AppleMusicURL.
func (s *Artist) SetAppleMusicURL(val OptNilString) {
	s.AppleMusicURL = val
}

// SetTidalURL sets the value of TidalURL.
func (s *Artist) SetTidalURL(val OptNilString) {
	s.TidalURL = val
}

// SetYoutubeMusicURL sets the value of YoutubeMusicURL.
func (s *Artist) SetYoutubeMusicURL(val OptNilString) {
	s.YoutubeMusicURL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Artist) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Artist) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

func (*Artist) getArtistRes() {}

type BadRequestTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s BadRequestTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*BadRequestTextPlain) addFriendRes()              {}
func (*BadRequestTextPlain) addToLibraryRes()           {}
func (*BadRequestTextPlain) getAlbumRes()               {}
func (*BadRequestTextPlain) getArtistRes()              {}
func (*BadRequestTextPlain) getCalendarListensRes()     {}
func (*BadRequestTextPlain) getListenSessionsRes()      {}
func (*BadRequestTextPlain) getTrackRes()               {}
func (*BadRequestTextPlain) getUserListenSessionsRes()  {}
func (*BadRequestTextPlain) registerRes()               {}
func (*BadRequestTextPlain) removeFriendRes()           {}
func (*BadRequestTextPlain) removeFromLibraryRes()      {}
func (*BadRequestTextPlain) searchTracksViaDetailsRes() {}
func (*BadRequestTextPlain) setActivityRes()            {}
func (*BadRequestTextPlain) setBestFriendRes()          {}
func (*BadRequestTextPlain) setBlockedRes()             {}
func (*BadRequestTextPlain) signInRes()                 {}
func (*BadRequestTextPlain) updateLibraryRes()          {}
func (*BadRequestTextPlain) updateUserRes()             {}

// Ref: #/components/schemas/BestFriendActionRequest
type BestFriendActionRequest struct {
	ID         uuid.UUID `json:"id"`
	BestFriend bool      `json:"best_friend"`
}

// GetID returns the value of ID.
func (s *BestFriendActionRequest) GetID() uuid.UUID {
	return s.ID
}

// GetBestFriend returns the value of BestFriend.
func (s *BestFriendActionRequest) GetBestFriend() bool {
	return s.BestFriend
}

// SetID sets the value of ID.
func (s *BestFriendActionRequest) SetID(val uuid.UUID) {
	s.ID = val
}

// SetBestFriend sets the value of BestFriend.
func (s *BestFriendActionRequest) SetBestFriend(val bool) {
	s.BestFriend = val
}

// Ref: #/components/schemas/BlockedActionRequest
type BlockedActionRequest struct {
	ID      uuid.UUID `json:"id"`
	Blocked bool      `json:"blocked"`
}

// GetID returns the value of ID.
func (s *BlockedActionRequest) GetID() uuid.UUID {
	return s.ID
}

// GetBlocked returns the value of Blocked.
func (s *BlockedActionRequest) GetBlocked() bool {
	return s.Blocked
}

// SetID sets the value of ID.
func (s *BlockedActionRequest) SetID(val uuid.UUID) {
	s.ID = val
}

// SetBlocked sets the value of Blocked.
func (s *BlockedActionRequest) SetBlocked(val bool) {
	s.Blocked = val
}

type ConflictTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ConflictTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*ConflictTextPlain) registerRes() {}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Human-readable error message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) getUserDetailsRes() {}
func (*ErrorResponse) validateTokenRes()  {}

type ForbiddenTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ForbiddenTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*ForbiddenTextPlain) addFriendRes()             {}
func (*ForbiddenTextPlain) getCalendarListensRes()    {}
func (*ForbiddenTextPlain) getUserListenSessionsRes() {}
func (*ForbiddenTextPlain) removeFriendRes()          {}
func (*ForbiddenTextPlain) setBestFriendRes()         {}
func (*ForbiddenTextPlain) setBlockedRes()            {}

// Request body for friend actions. At least one of 'id' or 'handle' must be provided to identify the
// target user.
// Ref: #/components/schemas/FriendActionRequest
type FriendActionRequest struct {
	// Target user's UUID. Optional if 'handle' is provided.
	ID OptNilUUID `json:"id"`
	// Target user's handle. Optional if 'id' is provided.
	Handle OptNilString `json:"handle"`
}

// GetID returns the value of ID.
func (s *FriendActionRequest) GetID() OptNilUUID {
	return s.ID
}

// GetHandle returns the value of Handle.
func (s *FriendActionRequest) GetHandle() OptNilString {
	return s.Handle
}

// SetID sets the value of ID.
func (s *FriendActionRequest) SetID(val OptNilUUID) {
	s.ID = val
}

// SetHandle sets the value of Handle.
func (s *FriendActionRequest) SetHandle(val OptNilString) {
	s.Handle = val
}

type GetAlbumApplicationJSONBadRequest ErrorResponse

func (*GetAlbumApplicationJSONBadRequest) getAlbumRes() {}

type GetAlbumApplicationJSONInternalServerError ErrorResponse

func (*GetAlbumApplicationJSONInternalServerError) getAlbumRes() {}

type GetAlbumApplicationJSONNotFound ErrorResponse

func (*GetAlbumApplicationJSONNotFound) getAlbumRes() {}

type GetAlbumApplicationJSONUnauthorized ErrorResponse

func (*GetAlbumApplicationJSONUnauthorized) getAlbumRes() {}

type GetArtistApplicationJSONBadRequest ErrorResponse

func (*GetArtistApplicationJSONBadRequest) getArtistRes() {}

type GetArtistApplicationJSONInternalServerError ErrorResponse

func (*GetArtistApplicationJSONInternalServerError) getArtistRes() {}

type GetArtistApplicationJSONNotFound ErrorResponse

func (*GetArtistApplicationJSONNotFound) getArtistRes() {}

type GetArtistApplicationJSONUnauthorized ErrorResponse

func (*GetArtistApplicationJSONUnauthorized) getArtistRes() {}

type GetCalendarListensApplicationJSONBadRequest ErrorResponse

func (*GetCalendarListensApplicationJSONBadRequest) getCalendarListensRes() {}

type GetCalendarListensApplicationJSONForbidden ErrorResponse

func (*GetCalendarListensApplicationJSONForbidden) getCalendarListensRes() {}

type GetCalendarListensApplicationJSONNotFound ErrorResponse

func (*GetCalendarListensApplicationJSONNotFound) getCalendarListensRes() {}

type GetCalendarListensOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetCalendarListensOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetCalendarListensOK) getCalendarListensRes() {}

type GetLibraryMetadataApplicationJSONInternalServerError ErrorResponse

func (*GetLibraryMetadataApplicationJSONInternalServerError) getLibraryMetadataRes() {}

type GetLibraryMetadataApplicationJSONUnauthorized ErrorResponse

func (*GetLibraryMetadataApplicationJSONUnauthorized) getLibraryMetadataRes() {}

type GetListenSessionsApplicationJSONBadRequest ErrorResponse

func (*GetListenSessionsApplicationJSONBadRequest) getListenSessionsRes() {}

type GetListenSessionsApplicationJSONInternalServerError ErrorResponse

func (*GetListenSessionsApplicationJSONInternalServerError) getListenSessionsRes() {}

type GetListenSessionsApplicationJSONUnauthorized ErrorResponse

func (*GetListenSessionsApplicationJSONUnauthorized) getListenSessionsRes() {}

type GetRelationsApplicationJSONInternalServerError ErrorResponse

func (*GetRelationsApplicationJSONInternalServerError) getRelationsRes() {}

type GetRelationsApplicationJSONUnauthorized ErrorResponse

func (*GetRelationsApplicationJSONUnauthorized) getRelationsRes() {}

type GetRelationsOKApplicationJSON []Relation

func (*GetRelationsOKApplicationJSON) getRelationsRes() {}

type GetTrackApplicationJSONBadRequest ErrorResponse

func (*GetTrackApplicationJSONBadRequest) getTrackRes() {}

type GetTrackApplicationJSONInternalServerError ErrorResponse

func (*GetTrackApplicationJSONInternalServerError) getTrackRes() {}

type GetTrackApplicationJSONNotFound ErrorResponse

func (*GetTrackApplicationJSONNotFound) getTrackRes() {}

type GetTrackApplicationJSONUnauthorized ErrorResponse

func (*GetTrackApplicationJSONUnauthorized) getTrackRes() {}

type GetUserListenSessionsApplicationJSONBadRequest ErrorResponse

func (*GetUserListenSessionsApplicationJSONBadRequest) getUserListenSessionsRes() {}

type GetUserListenSessionsApplicationJSONForbidden ErrorResponse

func (*GetUserListenSessionsApplicationJSONForbidden) getUserListenSessionsRes() {}

type GetUserListenSessionsApplicationJSONInternalServerError ErrorResponse

func (*GetUserListenSessionsApplicationJSONInternalServerError) getUserListenSessionsRes() {}

type GetUserListenSessionsApplicationJSONNotFound ErrorResponse

func (*GetUserListenSessionsApplicationJSONNotFound) getUserListenSessionsRes() {}

type GetUserListenSessionsApplicationJSONUnauthorized ErrorResponse

func (*GetUserListenSessionsApplicationJSONUnauthorized) getUserListenSessionsRes() {}

type InternalServerErrorTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s InternalServerErrorTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*InternalServerErrorTextPlain) addFriendRes()             {}
func (*InternalServerErrorTextPlain) addToLibraryRes()          {}
func (*InternalServerErrorTextPlain) getAlbumRes()              {}
func (*InternalServerErrorTextPlain) getArtistRes()             {}
func (*InternalServerErrorTextPlain) getLibraryMetadataRes()    {}
func (*InternalServerErrorTextPlain) getListenSessionsRes()     {}
func (*InternalServerErrorTextPlain) getRelationsRes()          {}
func (*InternalServerErrorTextPlain) getTrackRes()              {}
func (*InternalServerErrorTextPlain) getUserListenSessionsRes() {}
func (*InternalServerErrorTextPlain) joinFreeBetaRes()          {}
func (*InternalServerErrorTextPlain) registerRes()              {}
func (*InternalServerErrorTextPlain) removeFriendRes()          {}
func (*InternalServerErrorTextPlain) removeFromLibraryRes()     {}
func (*InternalServerErrorTextPlain) setActivityRes()           {}
func (*InternalServerErrorTextPlain) setBestFriendRes()         {}
func (*InternalServerErrorTextPlain) setBlockedRes()            {}
func (*InternalServerErrorTextPlain) signInRes()                {}
func (*InternalServerErrorTextPlain) updateLibraryRes()         {}
func (*InternalServerErrorTextPlain) updateUserRes()            {}

type JoinFreeBetaApplicationJSONInternalServerError ErrorResponse

func (*JoinFreeBetaApplicationJSONInternalServerError) joinFreeBetaRes() {}

type JoinFreeBetaApplicationJSONUnauthorized ErrorResponse

func (*JoinFreeBetaApplicationJSONUnauthorized) joinFreeBetaRes() {}

// JoinFreeBetaNoContent is response for JoinFreeBeta operation.
type JoinFreeBetaNoContent struct {
	HxLocation OptString
}

// GetHxLocation returns the value of HxLocation.
func (s *JoinFreeBetaNoContent) GetHxLocation() OptString {
	return s.HxLocation
}

// SetHxLocation sets the value of HxLocation.
func (s *JoinFreeBetaNoContent) SetHxLocation(val OptString) {
	s.HxLocation = val
}

func (*JoinFreeBetaNoContent) joinFreeBetaRes() {}

// Ref: #/components/schemas/LibraryAddAlbum
type LibraryAddAlbum struct {
	Album Album `json:"album"`
	// Client-provided reference ID for correlation in responses.
	ReferenceID OptInt64 `json:"reference_id"`
	// If true, skip deduplication and always create a new entity.
	ForceAdd OptBool `json:"force_add"`
}

// GetAlbum returns the value of Album.
func (s *LibraryAddAlbum) GetAlbum() Album {
	return s.Album
}

// GetReferenceID returns the value of ReferenceID.
func (s *LibraryAddAlbum) GetReferenceID() OptInt64 {
	return s.ReferenceID
}

// GetForceAdd returns the value of ForceAdd.
func (s *LibraryAddAlbum) GetForceAdd() OptBool {
	return s.ForceAdd
}

// SetAlbum sets the value of Album.
func (s *LibraryAddAlbum) SetAlbum(val Album) {
	s.Album = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *LibraryAddAlbum) SetReferenceID(val OptInt64) {
	s.ReferenceID = val
}

// SetForceAdd sets the value of ForceAdd.
func (s *LibraryAddAlbum) SetForceAdd(val OptBool) {
	s.ForceAdd = val
}

// Merged schema.
// Ref: #/components/schemas/LibraryAddAlbumTrack
type LibraryAddAlbumTrack struct {
	AlbumID          uuid.UUID  `json:"album_id"`
	TrackID          uuid.UUID  `json:"track_id"`
	DiscNumber       OptNilInt8 `json:"disc_number"`
	TrackNumber      OptNilInt8 `json:"track_number"`
	AlbumReferenceID int64      `json:"album_reference_id"`
	TrackReferenceID int64      `json:"track_reference_id"`
}

// GetAlbumID returns the value of AlbumID.
func (s *LibraryAddAlbumTrack) GetAlbumID() uuid.UUID {
	return s.AlbumID
}

// GetTrackID returns the value of TrackID.
func (s *LibraryAddAlbumTrack) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetDiscNumber returns the value of DiscNumber.
func (s *LibraryAddAlbumTrack) GetDiscNumber() OptNilInt8 {
	return s.DiscNumber
}

// GetTrackNumber returns the value of TrackNumber.
func (s *LibraryAddAlbumTrack) GetTrackNumber() OptNilInt8 {
	return s.TrackNumber
}

// GetAlbumReferenceID returns the value of AlbumReferenceID.
func (s *LibraryAddAlbumTrack) GetAlbumReferenceID() int64 {
	return s.AlbumReferenceID
}

// GetTrackReferenceID returns the value of TrackReferenceID.
func (s *LibraryAddAlbumTrack) GetTrackReferenceID() int64 {
	return s.TrackReferenceID
}

// SetAlbumID sets the value of AlbumID.
func (s *LibraryAddAlbumTrack) SetAlbumID(val uuid.UUID) {
	s.AlbumID = val
}

// SetTrackID sets the value of TrackID.
func (s *LibraryAddAlbumTrack) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetDiscNumber sets the value of DiscNumber.
func (s *LibraryAddAlbumTrack) SetDiscNumber(val OptNilInt8) {
	s.DiscNumber = val
}

// SetTrackNumber sets the value of TrackNumber.
func (s *LibraryAddAlbumTrack) SetTrackNumber(val OptNilInt8) {
	s.TrackNumber = val
}

// SetAlbumReferenceID sets the value of AlbumReferenceID.
func (s *LibraryAddAlbumTrack) SetAlbumReferenceID(val int64) {
	s.AlbumReferenceID = val
}

// SetTrackReferenceID sets the value of TrackReferenceID.
func (s *LibraryAddAlbumTrack) SetTrackReferenceID(val int64) {
	s.TrackReferenceID = val
}

// Ref: #/components/schemas/LibraryAddArtist
type LibraryAddArtist struct {
	Artist Artist `json:"artist"`
	// Client-provided reference ID for correlation in responses.
	ReferenceID OptInt64 `json:"reference_id"`
	// If true, skip deduplication and always create a new entity.
	ForceAdd OptBool `json:"force_add"`
}

// GetArtist returns the value of Artist.
func (s *LibraryAddArtist) GetArtist() Artist {
	return s.Artist
}

// GetReferenceID returns the value of ReferenceID.
func (s *LibraryAddArtist) GetReferenceID() OptInt64 {
	return s.ReferenceID
}

// GetForceAdd returns the value of ForceAdd.
func (s *LibraryAddArtist) GetForceAdd() OptBool {
	return s.ForceAdd
}

// SetArtist sets the value of Artist.
func (s *LibraryAddArtist) SetArtist(val Artist) {
	s.Artist = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *LibraryAddArtist) SetReferenceID(val OptInt64) {
	s.ReferenceID = val
}

// SetForceAdd sets the value of ForceAdd.
func (s *LibraryAddArtist) SetForceAdd(val OptBool) {
	s.ForceAdd = val
}

// Ref: #/components/schemas/LibraryAddID
type LibraryAddID struct {
	ID          OptUUID  `json:"id"`
	ReferenceID OptInt64 `json:"reference_id"`
}

// GetID returns the value of ID.
func (s *LibraryAddID) GetID() OptUUID {
	return s.ID
}

// GetReferenceID returns the value of ReferenceID.
func (s *LibraryAddID) GetReferenceID() OptInt64 {
	return s.ReferenceID
}

// SetID sets the value of ID.
func (s *LibraryAddID) SetID(val OptUUID) {
	s.ID = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *LibraryAddID) SetReferenceID(val OptInt64) {
	s.ReferenceID = val
}

// Ref: #/components/schemas/LibraryAddKV
type LibraryAddKV struct {
	Key   LibraryAddID `json:"key"`
	Value LibraryAddID `json:"value"`
}

// GetKey returns the value of Key.
func (s *LibraryAddKV) GetKey() LibraryAddID {
	return s.Key
}

// GetValue returns the value of Value.
func (s *LibraryAddKV) GetValue() LibraryAddID {
	return s.Value
}

// SetKey sets the value of Key.
func (s *LibraryAddKV) SetKey(val LibraryAddID) {
	s.Key = val
}

// SetValue sets the value of Value.
func (s *LibraryAddKV) SetValue(val LibraryAddID) {
	s.Value = val
}

// Ref: #/components/schemas/LibraryAddListen
type LibraryAddListen struct {
	Listen Listen `json:"listen"`
	// Client-provided reference ID for correlation in responses.
	ReferenceID OptInt64 `json:"reference_id"`
	// If true, skip deduplication and always create a new entity.
	ForceAdd OptBool `json:"force_add"`
}

// GetListen returns the value of Listen.
func (s *LibraryAddListen) GetListen() Listen {
	return s.Listen
}

// GetReferenceID returns the value of ReferenceID.
func (s *LibraryAddListen) GetReferenceID() OptInt64 {
	return s.ReferenceID
}

// GetForceAdd returns the value of ForceAdd.
func (s *LibraryAddListen) GetForceAdd() OptBool {
	return s.ForceAdd
}

// SetListen sets the value of Listen.
func (s *LibraryAddListen) SetListen(val Listen) {
	s.Listen = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *LibraryAddListen) SetReferenceID(val OptInt64) {
	s.ReferenceID = val
}

// SetForceAdd sets the value of ForceAdd.
func (s *LibraryAddListen) SetForceAdd(val OptBool) {
	s.ForceAdd = val
}

// Ref: #/components/schemas/LibraryAddRequest
type LibraryAddRequest struct {
	Tracks       []LibraryAddTrack      `json:"tracks"`
	Artists      []LibraryAddArtist     `json:"artists"`
	Albums       []LibraryAddAlbum      `json:"albums"`
	Listens      []LibraryAddListen     `json:"listens"`
	TrackArtists []LibraryAddKV         `json:"track_artists"`
	AlbumArtists []LibraryAddKV         `json:"album_artists"`
	ListenTracks []LibraryAddKV         `json:"listen_tracks"`
	AlbumTracks  []LibraryAddAlbumTrack `json:"album_tracks"`
}

// GetTracks returns the value of Tracks.
func (s *LibraryAddRequest) GetTracks() []LibraryAddTrack {
	return s.Tracks
}

// GetArtists returns the value of Artists.
func (s *LibraryAddRequest) GetArtists() []LibraryAddArtist {
	return s.Artists
}

// GetAlbums returns the value of Albums.
func (s *LibraryAddRequest) GetAlbums() []LibraryAddAlbum {
	return s.Albums
}

// GetListens returns the value of Listens.
func (s *LibraryAddRequest) GetListens() []LibraryAddListen {
	return s.Listens
}

// GetTrackArtists returns the value of TrackArtists.
func (s *LibraryAddRequest) GetTrackArtists() []LibraryAddKV {
	return s.TrackArtists
}

// GetAlbumArtists returns the value of AlbumArtists.
func (s *LibraryAddRequest) GetAlbumArtists() []LibraryAddKV {
	return s.AlbumArtists
}

// GetListenTracks returns the value of ListenTracks.
func (s *LibraryAddRequest) GetListenTracks() []LibraryAddKV {
	return s.ListenTracks
}

// GetAlbumTracks returns the value of AlbumTracks.
func (s *LibraryAddRequest) GetAlbumTracks() []LibraryAddAlbumTrack {
	return s.AlbumTracks
}

// SetTracks sets the value of Tracks.
func (s *LibraryAddRequest) SetTracks(val []LibraryAddTrack) {
	s.Tracks = val
}

// SetArtists sets the value of Artists.
func (s *LibraryAddRequest) SetArtists(val []LibraryAddArtist) {
	s.Artists = val
}

// SetAlbums sets the value of Albums.
func (s *LibraryAddRequest) SetAlbums(val []LibraryAddAlbum) {
	s.Albums = val
}

// SetListens sets the value of Listens.
func (s *LibraryAddRequest) SetListens(val []LibraryAddListen) {
	s.Listens = val
}

// SetTrackArtists sets the value of TrackArtists.
func (s *LibraryAddRequest) SetTrackArtists(val []LibraryAddKV) {
	s.TrackArtists = val
}

// SetAlbumArtists sets the value of AlbumArtists.
func (s *LibraryAddRequest) SetAlbumArtists(val []LibraryAddKV) {
	s.AlbumArtists = val
}

// SetListenTracks sets the value of ListenTracks.
func (s *LibraryAddRequest) SetListenTracks(val []LibraryAddKV) {
	s.ListenTracks = val
}

// SetAlbumTracks sets the value of AlbumTracks.
func (s *LibraryAddRequest) SetAlbumTracks(val []LibraryAddAlbumTrack) {
	s.AlbumTracks = val
}

// Ref: #/components/schemas/LibraryAddResponse
type LibraryAddResponse struct {
	Artists []LibraryAddResult `json:"artists"`
	Albums  []LibraryAddResult `json:"albums"`
	Tracks  []LibraryAddResult `json:"tracks"`
	Listens []LibraryAddResult `json:"listens"`
	Errors  []string           `json:"errors"`
}

// GetArtists returns the value of Artists.
func (s *LibraryAddResponse) GetArtists() []LibraryAddResult {
	return s.Artists
}

// GetAlbums returns the value of Albums.
func (s *LibraryAddResponse) GetAlbums() []LibraryAddResult {
	return s.Albums
}

// GetTracks returns the value of Tracks.
func (s *LibraryAddResponse) GetTracks() []LibraryAddResult {
	return s.Tracks
}

// GetListens returns the value of Listens.
func (s *LibraryAddResponse) GetListens() []LibraryAddResult {
	return s.Listens
}

// GetErrors returns the value of Errors.
func (s *LibraryAddResponse) GetErrors() []string {
	return s.Errors
}

// SetArtists sets the value of Artists.
func (s *LibraryAddResponse) SetArtists(val []LibraryAddResult) {
	s.Artists = val
}

// SetAlbums sets the value of Albums.
func (s *LibraryAddResponse) SetAlbums(val []LibraryAddResult) {
	s.Albums = val
}

// SetTracks sets the value of Tracks.
func (s *LibraryAddResponse) SetTracks(val []LibraryAddResult) {
	s.Tracks = val
}

// SetListens sets the value of Listens.
func (s *LibraryAddResponse) SetListens(val []LibraryAddResult) {
	s.Listens = val
}

// SetErrors sets the value of Errors.
func (s *LibraryAddResponse) SetErrors(val []string) {
	s.Errors = val
}

func (*LibraryAddResponse) addToLibraryRes() {}

// Ref: #/components/schemas/LibraryAddResult
type LibraryAddResult struct {
	// UUID of the created or resolved entity.
	ID uuid.UUID `json:"id"`
	// Reference ID provided in the request, echoed back for client correlation.
	ReferenceID OptInt64 `json:"reference_id"`
	// True if a new entity was created, false if an existing entity was resolved.
	Created bool `json:"created"`
}

// GetID returns the value of ID.
func (s *LibraryAddResult) GetID() uuid.UUID {
	return s.ID
}

// GetReferenceID returns the value of ReferenceID.
func (s *LibraryAddResult) GetReferenceID() OptInt64 {
	return s.ReferenceID
}

// GetCreated returns the value of Created.
func (s *LibraryAddResult) GetCreated() bool {
	return s.Created
}

// SetID sets the value of ID.
func (s *LibraryAddResult) SetID(val uuid.UUID) {
	s.ID = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *LibraryAddResult) SetReferenceID(val OptInt64) {
	s.ReferenceID = val
}

// SetCreated sets the value of Created.
func (s *LibraryAddResult) SetCreated(val bool) {
	s.Created = val
}

// Ref: #/components/schemas/LibraryAddTrack
type LibraryAddTrack struct {
	Track Track `json:"track"`
	// Client-provided reference ID for correlation in responses.
	ReferenceID OptInt64 `json:"reference_id"`
	// If true, skip deduplication and always create a new entity.
	ForceAdd OptBool `json:"force_add"`
}

// GetTrack returns the value of Track.
func (s *LibraryAddTrack) GetTrack() Track {
	return s.Track
}

// GetReferenceID returns the value of ReferenceID.
func (s *LibraryAddTrack) GetReferenceID() OptInt64 {
	return s.ReferenceID
}

// GetForceAdd returns the value of ForceAdd.
func (s *LibraryAddTrack) GetForceAdd() OptBool {
	return s.ForceAdd
}

// SetTrack sets the value of Track.
func (s *LibraryAddTrack) SetTrack(val Track) {
	s.Track = val
}

// SetReferenceID sets the value of ReferenceID.
func (s *LibraryAddTrack) SetReferenceID(val OptInt64) {
	s.ReferenceID = val
}

// SetForceAdd sets the value of ForceAdd.
func (s *LibraryAddTrack) SetForceAdd(val OptBool) {
	s.ForceAdd = val
}

// Ref: #/components/schemas/LibraryMetadataAlbum
type LibraryMetadataAlbum struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetID returns the value of ID.
func (s *LibraryMetadataAlbum) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *LibraryMetadataAlbum) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *LibraryMetadataAlbum) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *LibraryMetadataAlbum) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/LibraryMetadataArtist
type LibraryMetadataArtist struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetID returns the value of ID.
func (s *LibraryMetadataArtist) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *LibraryMetadataArtist) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *LibraryMetadataArtist) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *LibraryMetadataArtist) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/LibraryMetadataResponse
type LibraryMetadataResponse struct {
	Artists []LibraryMetadataArtist `json:"artists"`
	Albums  []LibraryMetadataAlbum  `json:"albums"`
	Tracks  []LibraryMetadataTrack  `json:"tracks"`
}

// GetArtists returns the value of Artists.
func (s *LibraryMetadataResponse) GetArtists() []LibraryMetadataArtist {
	return s.Artists
}

// GetAlbums returns the value of Albums.
func (s *LibraryMetadataResponse) GetAlbums() []LibraryMetadataAlbum {
	return s.Albums
}

// GetTracks returns the value of Tracks.
func (s *LibraryMetadataResponse) GetTracks() []LibraryMetadataTrack {
	return s.Tracks
}

// SetArtists sets the value of Artists.
func (s *LibraryMetadataResponse) SetArtists(val []LibraryMetadataArtist) {
	s.Artists = val
}

// SetAlbums sets the value of Albums.
func (s *LibraryMetadataResponse) SetAlbums(val []LibraryMetadataAlbum) {
	s.Albums = val
}

// SetTracks sets the value of Tracks.
func (s *LibraryMetadataResponse) SetTracks(val []LibraryMetadataTrack) {
	s.Tracks = val
}

func (*LibraryMetadataResponse) getLibraryMetadataRes() {}

// Ref: #/components/schemas/LibraryMetadataTrack
type LibraryMetadataTrack struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Seconds   OptNilUint16 `json:"seconds"`
	AlbumIds  []uuid.UUID  `json:"album_ids"`
	ArtistIds []uuid.UUID  `json:"artist_ids"`
}

// GetID returns the value of ID.
func (s *LibraryMetadataTrack) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *LibraryMetadataTrack) GetName() string {
	return s.Name
}

// GetSeconds returns the value of Seconds.
func (s *LibraryMetadataTrack) GetSeconds() OptNilUint16 {
	return s.Seconds
}

// GetAlbumIds returns the value of AlbumIds.
func (s *LibraryMetadataTrack) GetAlbumIds() []uuid.UUID {
	return s.AlbumIds
}

// GetArtistIds returns the value of ArtistIds.
func (s *LibraryMetadataTrack) GetArtistIds() []uuid.UUID {
	return s.ArtistIds
}

// SetID sets the value of ID.
func (s *LibraryMetadataTrack) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *LibraryMetadataTrack) SetName(val string) {
	s.Name = val
}

// SetSeconds sets the value of Seconds.
func (s *LibraryMetadataTrack) SetSeconds(val OptNilUint16) {
	s.Seconds = val
}

// SetAlbumIds sets the value of AlbumIds.
func (s *LibraryMetadataTrack) SetAlbumIds(val []uuid.UUID) {
	s.AlbumIds = val
}

// SetArtistIds sets the value of ArtistIds.
func (s *LibraryMetadataTrack) SetArtistIds(val []uuid.UUID) {
	s.ArtistIds = val
}

// Ref: #/components/schemas/LibraryRemoveRequest
type LibraryRemoveRequest struct {
	TrackIds  []uuid.UUID `json:"track_ids"`
	AlbumIds  []uuid.UUID `json:"album_ids"`
	ArtistIds []uuid.UUID `json:"artist_ids"`
	ListenIds []int64     `json:"listen_ids"`
}

// GetTrackIds returns the value of TrackIds.
func (s *LibraryRemoveRequest) GetTrackIds() []uuid.UUID {
	return s.TrackIds
}

// GetAlbumIds returns the value of AlbumIds.
func (s *LibraryRemoveRequest) GetAlbumIds() []uuid.UUID {
	return s.AlbumIds
}

// GetArtistIds returns the value of ArtistIds.
func (s *LibraryRemoveRequest) GetArtistIds() []uuid.UUID {
	return s.ArtistIds
}

// GetListenIds returns the value of ListenIds.
func (s *LibraryRemoveRequest) GetListenIds() []int64 {
	return s.ListenIds
}

// SetTrackIds sets the value of TrackIds.
func (s *LibraryRemoveRequest) SetTrackIds(val []uuid.UUID) {
	s.TrackIds = val
}

// SetAlbumIds sets the value of AlbumIds.
func (s *LibraryRemoveRequest) SetAlbumIds(val []uuid.UUID) {
	s.AlbumIds = val
}

// SetArtistIds sets the value of ArtistIds.
func (s *LibraryRemoveRequest) SetArtistIds(val []uuid.UUID) {
	s.ArtistIds = val
}

// SetListenIds sets the value of ListenIds.
func (s *LibraryRemoveRequest) SetListenIds(val []int64) {
	s.ListenIds = val
}

// Ref: #/components/schemas/LibraryUpdateRequest
type LibraryUpdateRequest struct {
	Tracks             []Track       `json:"tracks"`
	Artists            []Artist      `json:"artists"`
	Albums             []Album       `json:"albums"`
	TrackArtists       []TrackArtist `json:"track_artists"`
	AlbumArtists       []AlbumArtist `json:"album_artists"`
	AlbumTracks        []AlbumTrack  `json:"album_tracks"`
	AppendTrackArtists OptBool       `json:"append_track_artists"`
	AppendAlbumArtists OptBool       `json:"append_album_artists"`
	AppendAlbumTracks  OptBool       `json:"append_album_tracks"`
}

// GetTracks returns the value of Tracks.
func (s *LibraryUpdateRequest) GetTracks() []Track {
	return s.Tracks
}

// GetArtists returns the value of Artists.
func (s *LibraryUpdateRequest) GetArtists() []Artist {
	return s.Artists
}

// GetAlbums returns the value of Albums.
func (s *LibraryUpdateRequest) GetAlbums() []Album {
	return s.Albums
}

// GetTrackArtists returns the value of TrackArtists.
func (s *LibraryUpdateRequest) GetTrackArtists() []TrackArtist {
	return s.TrackArtists
}

// GetAlbumArtists returns the value of AlbumArtists.
func (s *LibraryUpdateRequest) GetAlbumArtists() []AlbumArtist {
	return s.AlbumArtists
}

// GetAlbumTracks returns the value of AlbumTracks.
func (s *LibraryUpdateRequest) GetAlbumTracks() []AlbumTrack {
	return s.AlbumTracks
}

// GetAppendTrackArtists returns the value of AppendTrackArtists.
func (s *LibraryUpdateRequest) GetAppendTrackArtists() OptBool {
	return s.AppendTrackArtists
}

// GetAppendAlbumArtists returns the value of AppendAlbumArtists.
func (s *LibraryUpdateRequest) GetAppendAlbumArtists() OptBool {
	return s.AppendAlbumArtists
}

// GetAppendAlbumTracks returns the value of AppendAlbumTracks.
func (s *LibraryUpdateRequest) GetAppendAlbumTracks() OptBool {
	return s.AppendAlbumTracks
}

// SetTracks sets the value of Tracks.
func (s *LibraryUpdateRequest) SetTracks(val []Track) {
	s.Tracks = val
}

// SetArtists sets the value of Artists.
func (s *LibraryUpdateRequest) SetArtists(val []Artist) {
	s.Artists = val
}

// SetAlbums sets the value of Albums.
func (s *LibraryUpdateRequest) SetAlbums(val []Album) {
	s.Albums = val
}

// SetTrackArtists sets the value of TrackArtists.
func (s *LibraryUpdateRequest) SetTrackArtists(val []TrackArtist) {
	s.TrackArtists = val
}

// SetAlbumArtists sets the value of AlbumArtists.
func (s *LibraryUpdateRequest) SetAlbumArtists(val []AlbumArtist) {
	s.AlbumArtists = val
}

// SetAlbumTracks sets the value of AlbumTracks.
func (s *LibraryUpdateRequest) SetAlbumTracks(val []AlbumTrack) {
	s.AlbumTracks = val
}

// SetAppendTrackArtists sets the value of AppendTrackArtists.
func (s *LibraryUpdateRequest) SetAppendTrackArtists(val OptBool) {
	s.AppendTrackArtists = val
}

// SetAppendAlbumArtists sets the value of AppendAlbumArtists.
func (s *LibraryUpdateRequest) SetAppendAlbumArtists(val OptBool) {
	s.AppendAlbumArtists = val
}

// SetAppendAlbumTracks sets the value of AppendAlbumTracks.
func (s *LibraryUpdateRequest) SetAppendAlbumTracks(val OptBool) {
	s.AppendAlbumTracks = val
}

// Ref: #/components/schemas/LibraryUpdateResponse
type LibraryUpdateResponse struct {
	Artists []Artist `json:"artists"`
	Albums  []Album  `json:"albums"`
	Tracks  []Track  `json:"tracks"`
	Errors  []string `json:"errors"`
}

// GetArtists returns the value of Artists.
func (s *LibraryUpdateResponse) GetArtists() []Artist {
	return s.Artists
}

// GetAlbums returns the value of Albums.
func (s *LibraryUpdateResponse) GetAlbums() []Album {
	return s.Albums
}

// GetTracks returns the value of Tracks.
func (s *LibraryUpdateResponse) GetTracks() []Track {
	return s.Tracks
}

// GetErrors returns the value of Errors.
func (s *LibraryUpdateResponse) GetErrors() []string {
	return s.Errors
}

// SetArtists sets the value of Artists.
func (s *LibraryUpdateResponse) SetArtists(val []Artist) {
	s.Artists = val
}

// SetAlbums sets the value of Albums.
func (s *LibraryUpdateResponse) SetAlbums(val []Album) {
	s.Albums = val
}

// SetTracks sets the value of Tracks.
func (s *LibraryUpdateResponse) SetTracks(val []Track) {
	s.Tracks = val
}

// SetErrors sets the value of Errors.
func (s *LibraryUpdateResponse) SetErrors(val []string) {
	s.Errors = val
}

func (*LibraryUpdateResponse) updateLibraryRes() {}

// Ref: #/components/schemas/Listen
type Listen struct {
	ListenID  int64          `json:"listen_id"`
	UserID    uuid.UUID      `json:"user_id"`
	TrackID   uuid.UUID      `json:"track_id"`
	Seconds   uint16         `json:"seconds"`
	Method    ListenMethod   `json:"method"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt OptNilDateTime `json:"updated_at"`
}

// GetListenID returns the value of ListenID.
func (s *Listen) GetListenID() int64 {
	return s.ListenID
}

// GetUserID returns the value of UserID.
func (s *Listen) GetUserID() uuid.UUID {
	return s.UserID
}

// GetTrackID returns the value of TrackID.
func (s *Listen) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetSeconds returns the value of Seconds.
func (s *Listen) GetSeconds() uint16 {
	return s.Seconds
}

// GetMethod returns the value of Method.
func (s *Listen) GetMethod() ListenMethod {
	return s.Method
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Listen) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Listen) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetListenID sets the value of ListenID.
func (s *Listen) SetListenID(val int64) {
	s.ListenID = val
}

// SetUserID sets the value of UserID.
func (s *Listen) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetTrackID sets the value of TrackID.
func (s *Listen) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetSeconds sets the value of Seconds.
func (s *Listen) SetSeconds(val uint16) {
	s.Seconds = val
}

// SetMethod sets the value of Method.
func (s *Listen) SetMethod(val ListenMethod) {
	s.Method = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Listen) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Listen) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

// 0=API: listen was added via API
// 1=App: listen was added via an official client application
// 2=Spotify: listen was imported from Spotify
// 3=AppleMusic: listen was imported from Apple Music
// 4=Last: listen was imported from Last.
// Ref: #/components/schemas/ListenMethod
type ListenMethod uint8

const (
	ListenMethod0 ListenMethod = 0
	ListenMethod1 ListenMethod = 1
	ListenMethod2 ListenMethod = 2
	ListenMethod3 ListenMethod = 3
	ListenMethod4 ListenMethod = 4
)

// AllValues returns all ListenMethod values.
func (ListenMethod) AllValues() []ListenMethod {
	return []ListenMethod{
		ListenMethod0,
		ListenMethod1,
		ListenMethod2,
		ListenMethod3,
		ListenMethod4,
	}
}

// Ref: #/components/schemas/ListensSessionsRequest
type ListensSessionsRequest struct {
	// Start of time range filter.
	Start OptDateTime `json:"start"`
	// End of time range filter.
	End OptDateTime `json:"end"`
	// Minimum amount of listens to be fetched. The start parameter's value may not be respected to
	// achieve this.
	Minimum OptInt64 `json:"minimum"`
	// Maximum amount of listens to be fetched.
	Limit OptInt64 `json:"limit"`
}

// GetStart returns the value of Start.
func (s *ListensSessionsRequest) GetStart() OptDateTime {
	return s.Start
}

// GetEnd returns the value of End.
func (s *ListensSessionsRequest) GetEnd() OptDateTime {
	return s.End
}

// GetMinimum returns the value of Minimum.
func (s *ListensSessionsRequest) GetMinimum() OptInt64 {
	return s.Minimum
}

// GetLimit returns the value of Limit.
func (s *ListensSessionsRequest) GetLimit() OptInt64 {
	return s.Limit
}

// SetStart sets the value of Start.
func (s *ListensSessionsRequest) SetStart(val OptDateTime) {
	s.Start = val
}

// SetEnd sets the value of End.
func (s *ListensSessionsRequest) SetEnd(val OptDateTime) {
	s.End = val
}

// SetMinimum sets the value of Minimum.
func (s *ListensSessionsRequest) SetMinimum(val OptInt64) {
	s.Minimum = val
}

// SetLimit sets the value of Limit.
func (s *ListensSessionsRequest) SetLimit(val OptInt64) {
	s.Limit = val
}

// Ref: #/components/responses/NoContent
type NoContent struct{}

func (*NoContent) removeFriendRes()      {}
func (*NoContent) removeFromLibraryRes() {}
func (*NoContent) setActivityRes()       {}
func (*NoContent) setBestFriendRes()     {}
func (*NoContent) setBlockedRes()        {}
func (*NoContent) updateUserRes()        {}
func (*NoContent) validateTokenRes()     {}

type NotFoundTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s NotFoundTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*NotFoundTextPlain) addFriendRes()             {}
func (*NotFoundTextPlain) getAlbumRes()              {}
func (*NotFoundTextPlain) getArtistRes()             {}
func (*NotFoundTextPlain) getCalendarListensRes()    {}
func (*NotFoundTextPlain) getTrackRes()              {}
func (*NotFoundTextPlain) getUserListenSessionsRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilBool returns new OptNilBool with value set to v.
func NewOptNilBool(v bool) OptNilBool {
	return OptNilBool{
		Value: v,
		Set:   true,
	}
}

// OptNilBool is optional nullable bool.
type OptNilBool struct {
	Value bool
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBool was set.
func (o OptNilBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBool) SetTo(v bool) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilBool) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilBool) SetToNull() {
	o.Set = true
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt8 returns new OptNilInt8 with value set to v.
func NewOptNilInt8(v int8) OptNilInt8 {
	return OptNilInt8{
		Value: v,
		Set:   true,
	}
}

// OptNilInt8 is optional nullable int8.
type OptNilInt8 struct {
	Value int8
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt8 was set.
func (o OptNilInt8) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt8) Reset() {
	var v int8
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt8) SetTo(v int8) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt8) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt8) SetToNull() {
	o.Set = true
	o.Null = true
	var v int8
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt8) Get() (v int8, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt8) Or(d int8) int8 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUint16 returns new OptNilUint16 with value set to v.
func NewOptNilUint16(v uint16) OptNilUint16 {
	return OptNilUint16{
		Value: v,
		Set:   true,
	}
}

// OptNilUint16 is optional nullable uint16.
type OptNilUint16 struct {
	Value uint16
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUint16 was set.
func (o OptNilUint16) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUint16) Reset() {
	var v uint16
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUint16) SetTo(v uint16) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUint16) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUint16) SetToNull() {
	o.Set = true
	o.Null = true
	var v uint16
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUint16) Get() (v uint16, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUint16) Or(d uint16) uint16 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUint16 returns new OptUint16 with value set to v.
func NewOptUint16(v uint16) OptUint16 {
	return OptUint16{
		Value: v,
		Set:   true,
	}
}

// OptUint16 is optional uint16.
type OptUint16 struct {
	Value uint16
	Set   bool
}

// IsSet returns true if OptUint16 was set.
func (o OptUint16) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUint16) Reset() {
	var v uint16
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUint16) SetTo(v uint16) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUint16) Get() (v uint16, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUint16) Or(d uint16) uint16 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUserVisibility returns new OptUserVisibility with value set to v.
func NewOptUserVisibility(v UserVisibility) OptUserVisibility {
	return OptUserVisibility{
		Value: v,
		Set:   true,
	}
}

// OptUserVisibility is optional UserVisibility.
type OptUserVisibility struct {
	Value UserVisibility
	Set   bool
}

// IsSet returns true if OptUserVisibility was set.
func (o OptUserVisibility) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUserVisibility) Reset() {
	var v UserVisibility
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUserVisibility) SetTo(v UserVisibility) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUserVisibility) Get() (v UserVisibility, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUserVisibility) Or(d UserVisibility) UserVisibility {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RegisterApplicationJSONBadRequest ErrorResponse

func (*RegisterApplicationJSONBadRequest) registerRes() {}

type RegisterApplicationJSONConflict ErrorResponse

func (*RegisterApplicationJSONConflict) registerRes() {}

type RegisterApplicationJSONInternalServerError ErrorResponse

func (*RegisterApplicationJSONInternalServerError) registerRes() {}

// RegisterCreated is response for Register operation.
type RegisterCreated struct {
	HxLocation OptString
}

// GetHxLocation returns the value of HxLocation.
func (s *RegisterCreated) GetHxLocation() OptString {
	return s.HxLocation
}

// SetHxLocation sets the value of HxLocation.
func (s *RegisterCreated) SetHxLocation(val OptString) {
	s.HxLocation = val
}

func (*RegisterCreated) registerRes() {}

// Ref: #/components/schemas/RegisterRequest
type RegisterRequest struct {
	// 2+ Unicode letters, spaces allowed.
	Name  string `json:"name"`
	Email string `json:"email"`
	// 8+ characters, must contain uppercase, lowercase, digit, and special character.
	Password string `json:"password"`
}

// GetName returns the value of Name.
func (s *RegisterRequest) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *RegisterRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *RegisterRequest) GetPassword() string {
	return s.Password
}

// SetName sets the value of Name.
func (s *RegisterRequest) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *RegisterRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *RegisterRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/Relation
type Relation struct {
	SourceID  uuid.UUID      `json:"source_id"`
	TargetID  uuid.UUID      `json:"target_id"`
	Relation  UserRelation   `json:"relation"`
	UpdatedAt OptNilDateTime `json:"updated_at"`
}

// GetSourceID returns the value of SourceID.
func (s *Relation) GetSourceID() uuid.UUID {
	return s.SourceID
}

// GetTargetID returns the value of TargetID.
func (s *Relation) GetTargetID() uuid.UUID {
	return s.TargetID
}

// GetRelation returns the value of Relation.
func (s *Relation) GetRelation() UserRelation {
	return s.Relation
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Relation) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetSourceID sets the value of SourceID.
func (s *Relation) SetSourceID(val uuid.UUID) {
	s.SourceID = val
}

// SetTargetID sets the value of TargetID.
func (s *Relation) SetTargetID(val uuid.UUID) {
	s.TargetID = val
}

// SetRelation sets the value of Relation.
func (s *Relation) SetRelation(val UserRelation) {
	s.Relation = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Relation) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

func (*Relation) addFriendRes() {}

type RemoveFriendApplicationJSONBadRequest ErrorResponse

func (*RemoveFriendApplicationJSONBadRequest) removeFriendRes() {}

type RemoveFriendApplicationJSONForbidden ErrorResponse

func (*RemoveFriendApplicationJSONForbidden) removeFriendRes() {}

type RemoveFriendApplicationJSONInternalServerError ErrorResponse

func (*RemoveFriendApplicationJSONInternalServerError) removeFriendRes() {}

type RemoveFriendApplicationJSONUnauthorized ErrorResponse

func (*RemoveFriendApplicationJSONUnauthorized) removeFriendRes() {}

type RemoveFriendReq struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *RemoveFriendReq) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *RemoveFriendReq) SetID(val uuid.UUID) {
	s.ID = val
}

type RemoveFromLibraryApplicationJSONBadRequest ErrorResponse

func (*RemoveFromLibraryApplicationJSONBadRequest) removeFromLibraryRes() {}

type RemoveFromLibraryApplicationJSONInternalServerError ErrorResponse

func (*RemoveFromLibraryApplicationJSONInternalServerError) removeFromLibraryRes() {}

type RemoveFromLibraryApplicationJSONUnauthorized ErrorResponse

func (*RemoveFromLibraryApplicationJSONUnauthorized) removeFromLibraryRes() {}

// Merged schema.
// Ref: #/components/schemas/SearchTrackResult
type SearchTrackResult struct {
	TrackID         uuid.UUID      `json:"track_id"`
	UserID          OptNilUUID     `json:"user_id"`
	Name            string         `json:"name"`
	Seconds         OptNilUint16   `json:"seconds"`
	Lyrics          OptNilString   `json:"lyrics"`
	Explicit        OptNilBool     `json:"explicit"`
	MusicbrainzID   OptNilUUID     `json:"musicbrainz_id"`
	SpotifyURL      OptNilString   `json:"spotify_url"`
	AppleMusicURL   OptNilString   `json:"apple_music_url"`
	TidalURL        OptNilString   `json:"tidal_url"`
	YoutubeMusicURL OptNilString   `json:"youtube_music_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       OptNilDateTime `json:"updated_at"`
	// Confidence score (0-100).
	Confidence int `json:"confidence"`
}

// GetTrackID returns the value of TrackID.
func (s *SearchTrackResult) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetUserID returns the value of UserID.
func (s *SearchTrackResult) GetUserID() OptNilUUID {
	return s.UserID
}

// GetName returns the value of Name.
func (s *SearchTrackResult) GetName() string {
	return s.Name
}

// GetSeconds returns the value of Seconds.
func (s *SearchTrackResult) GetSeconds() OptNilUint16 {
	return s.Seconds
}

// GetLyrics returns the value of Lyrics.
func (s *SearchTrackResult) GetLyrics() OptNilString {
	return s.Lyrics
}

// GetExplicit returns the value of Explicit.
func (s *SearchTrackResult) GetExplicit() OptNilBool {
	return s.Explicit
}

// GetMusicbrainzID returns the value of MusicbrainzID.
func (s *SearchTrackResult) GetMusicbrainzID() OptNilUUID {
	return s.MusicbrainzID
}

// GetSpotifyURL returns the value of SpotifyURL.
func (s *SearchTrackResult) GetSpotifyURL() OptNilString {
	return s.SpotifyURL
}

// GetAppleMusicURL returns the value of AppleMusicURL.
func (s *SearchTrackResult) GetAppleMusicURL() OptNilString {
	return s.AppleMusicURL
}

// GetTidalURL returns the value of TidalURL.
func (s *SearchTrackResult) GetTidalURL() OptNilString {
	return s.TidalURL
}

// GetYoutubeMusicURL returns the value of YoutubeMusicURL.
func (s *SearchTrackResult) GetYoutubeMusicURL() OptNilString {
	return s.YoutubeMusicURL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SearchTrackResult) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SearchTrackResult) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// GetConfidence returns the value of Confidence.
func (s *SearchTrackResult) GetConfidence() int {
	return s.Confidence
}

// SetTrackID sets the value of TrackID.
func (s *SearchTrackResult) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetUserID sets the value of UserID.
func (s *SearchTrackResult) SetUserID(val OptNilUUID) {
	s.UserID = val
}

// SetName sets the value of Name.
func (s *SearchTrackResult) SetName(val string) {
	s.Name = val
}

// SetSeconds sets the value of Seconds.
func (s *SearchTrackResult) SetSeconds(val OptNilUint16) {
	s.Seconds = val
}

// SetLyrics sets the value of Lyrics.
func (s *SearchTrackResult) SetLyrics(val OptNilString) {
	s.Lyrics = val
}

// SetExplicit sets the value of Explicit.
func (s *SearchTrackResult) SetExplicit(val OptNilBool) {
	s.Explicit = val
}

// SetMusicbrainzID sets the value of MusicbrainzID.
func (s *SearchTrackResult) SetMusicbrainzID(val OptNilUUID) {
	s.MusicbrainzID = val
}

// SetSpotifyURL sets the value of SpotifyURL.
func (s *SearchTrackResult) SetSpotifyURL(val OptNilString) {
	s.SpotifyURL = val
}

// SetAppleMusicURL sets the value of AppleMusicURL.
func (s *SearchTrackResult) SetAppleMusicURL(val OptNilString) {
	s.AppleMusicURL = val
}

// SetTidalURL sets the value of TidalURL.
func (s *SearchTrackResult) SetTidalURL(val OptNilString) {
	s.TidalURL = val
}

// SetYoutubeMusicURL sets the value of YoutubeMusicURL.
func (s *SearchTrackResult) SetYoutubeMusicURL(val OptNilString) {
	s.YoutubeMusicURL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SearchTrackResult) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SearchTrackResult) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

// SetConfidence sets the value of Confidence.
func (s *SearchTrackResult) SetConfidence(val int) {
	s.Confidence = val
}

// Ref: #/components/schemas/SearchTracksRequest
type SearchTracksRequest struct {
	TrackName   string    `json:"track_name"`
	ArtistNames []string  `json:"artist_names"`
	AlbumName   OptString `json:"album_name"`
	Seconds     OptUint16 `json:"seconds"`
}

// GetTrackName returns the value of TrackName.
func (s *SearchTracksRequest) GetTrackName() string {
	return s.TrackName
}

// GetArtistNames returns the value of ArtistNames.
func (s *SearchTracksRequest) GetArtistNames() []string {
	return s.ArtistNames
}

// GetAlbumName returns the value of AlbumName.
func (s *SearchTracksRequest) GetAlbumName() OptString {
	return s.AlbumName
}

// GetSeconds returns the value of Seconds.
func (s *SearchTracksRequest) GetSeconds() OptUint16 {
	return s.Seconds
}

// SetTrackName sets the value of TrackName.
func (s *SearchTracksRequest) SetTrackName(val string) {
	s.TrackName = val
}

// SetArtistNames sets the value of ArtistNames.
func (s *SearchTracksRequest) SetArtistNames(val []string) {
	s.ArtistNames = val
}

// SetAlbumName sets the value of AlbumName.
func (s *SearchTracksRequest) SetAlbumName(val OptString) {
	s.AlbumName = val
}

// SetSeconds sets the value of Seconds.
func (s *SearchTracksRequest) SetSeconds(val OptUint16) {
	s.Seconds = val
}

type SearchTracksViaDetailsApplicationJSONBadRequest ErrorResponse

func (*SearchTracksViaDetailsApplicationJSONBadRequest) searchTracksViaDetailsRes() {}

type SearchTracksViaDetailsApplicationJSONUnauthorized ErrorResponse

func (*SearchTracksViaDetailsApplicationJSONUnauthorized) searchTracksViaDetailsRes() {}

type SearchTracksViaDetailsOKApplicationJSON []SearchTrackResult

func (*SearchTracksViaDetailsOKApplicationJSON) searchTracksViaDetailsRes() {}

// Ref: #/components/schemas/Session
type Session struct {
	// Unique identifier for this listening session.
	ID int32 `json:"id"`
	// Timestamp when the session started.
	Start time.Time `json:"start"`
	// Timestamp when the session ended.
	End time.Time `json:"end"`
	// List of listens in this session, ordered chronologically.
	Listens []SessionListen `json:"listens"`
	// UUID of the most-listened artist in this session.
	TopArtist OptNilUUID `json:"top_artist"`
	// UUID of the most-listened album in this session.
	TopAlbum OptNilUUID `json:"top_album"`
	// True if this session is incomplete (cut off by pagination limit).
	Partial OptNilBool `json:"partial"`
}

// GetID returns the value of ID.
func (s *Session) GetID() int32 {
	return s.ID
}

// GetStart returns the value of Start.
func (s *Session) GetStart() time.Time {
	return s.Start
}

// GetEnd returns the value of End.
func (s *Session) GetEnd() time.Time {
	return s.End
}

// GetListens returns the value of Listens.
func (s *Session) GetListens() []SessionListen {
	return s.Listens
}

// GetTopArtist returns the value of TopArtist.
func (s *Session) GetTopArtist() OptNilUUID {
	return s.TopArtist
}

// GetTopAlbum returns the value of TopAlbum.
func (s *Session) GetTopAlbum() OptNilUUID {
	return s.TopAlbum
}

// GetPartial returns the value of Partial.
func (s *Session) GetPartial() OptNilBool {
	return s.Partial
}

// SetID sets the value of ID.
func (s *Session) SetID(val int32) {
	s.ID = val
}

// SetStart sets the value of Start.
func (s *Session) SetStart(val time.Time) {
	s.Start = val
}

// SetEnd sets the value of End.
func (s *Session) SetEnd(val time.Time) {
	s.End = val
}

// SetListens sets the value of Listens.
func (s *Session) SetListens(val []SessionListen) {
	s.Listens = val
}

// SetTopArtist sets the value of TopArtist.
func (s *Session) SetTopArtist(val OptNilUUID) {
	s.TopArtist = val
}

// SetTopAlbum sets the value of TopAlbum.
func (s *Session) SetTopAlbum(val OptNilUUID) {
	s.TopAlbum = val
}

// SetPartial sets the value of Partial.
func (s *Session) SetPartial(val OptNilBool) {
	s.Partial = val
}

// Ref: #/components/schemas/SessionAlbum
type SessionAlbum struct {
	// Album UUID.
	ID uuid.UUID `json:"id"`
	// Album name.
	Name string `json:"name"`
	// URL to the album cover image.
	ImageURL OptNilString `json:"image_url"`
}

// GetID returns the value of ID.
func (s *SessionAlbum) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *SessionAlbum) GetName() string {
	return s.Name
}

// GetImageURL returns the value of ImageURL.
func (s *SessionAlbum) GetImageURL() OptNilString {
	return s.ImageURL
}

// SetID sets the value of ID.
func (s *SessionAlbum) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SessionAlbum) SetName(val string) {
	s.Name = val
}

// SetImageURL sets the value of ImageURL.
func (s *SessionAlbum) SetImageURL(val OptNilString) {
	s.ImageURL = val
}

// Ref: #/components/schemas/SessionArtist
type SessionArtist struct {
	// Artist UUID.
	ID uuid.UUID `json:"id"`
	// Artist name.
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *SessionArtist) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *SessionArtist) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *SessionArtist) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SessionArtist) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/SessionDay
type SessionDay struct {
	// Calendar date for this group of sessions.
	Date time.Time `json:"date"`
	// Sessions for this day, ordered newest first.
	Sessions []Session `json:"sessions"`
}

// GetDate returns the value of Date.
func (s *SessionDay) GetDate() time.Time {
	return s.Date
}

// GetSessions returns the value of Sessions.
func (s *SessionDay) GetSessions() []Session {
	return s.Sessions
}

// SetDate sets the value of Date.
func (s *SessionDay) SetDate(val time.Time) {
	s.Date = val
}

// SetSessions sets the value of Sessions.
func (s *SessionDay) SetSessions(val []Session) {
	s.Sessions = val
}

// Ref: #/components/schemas/SessionListen
type SessionListen struct {
	// Unique identifier for this listen event.
	ID int32 `json:"id"`
	// UUID of the track listened to.
	Track uuid.UUID `json:"track"`
	// Timestamp when playback started.
	Start time.Time `json:"start"`
	// Timestamp when playback ended.
	End time.Time `json:"end"`
}

// GetID returns the value of ID.
func (s *SessionListen) GetID() int32 {
	return s.ID
}

// GetTrack returns the value of Track.
func (s *SessionListen) GetTrack() uuid.UUID {
	return s.Track
}

// GetStart returns the value of Start.
func (s *SessionListen) GetStart() time.Time {
	return s.Start
}

// GetEnd returns the value of End.
func (s *SessionListen) GetEnd() time.Time {
	return s.End
}

// SetID sets the value of ID.
func (s *SessionListen) SetID(val int32) {
	s.ID = val
}

// SetTrack sets the value of Track.
func (s *SessionListen) SetTrack(val uuid.UUID) {
	s.Track = val
}

// SetStart sets the value of Start.
func (s *SessionListen) SetStart(val time.Time) {
	s.Start = val
}

// SetEnd sets the value of End.
func (s *SessionListen) SetEnd(val time.Time) {
	s.End = val
}

// Ref: #/components/schemas/SessionTrack
type SessionTrack struct {
	// Track UUID.
	ID uuid.UUID `json:"id"`
	// Track name.
	Name string `json:"name"`
	// List of artist UUIDs for this track.
	Artists []uuid.UUID `json:"artists"`
	// Album UUID, if available.
	Album OptNilUUID `json:"album"`
	// Whether the track has explicit content.
	Explicit OptNilBool `json:"explicit"`
}

// GetID returns the value of ID.
func (s *SessionTrack) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *SessionTrack) GetName() string {
	return s.Name
}

// GetArtists returns the value of Artists.
func (s *SessionTrack) GetArtists() []uuid.UUID {
	return s.Artists
}

// GetAlbum returns the value of Album.
func (s *SessionTrack) GetAlbum() OptNilUUID {
	return s.Album
}

// GetExplicit returns the value of Explicit.
func (s *SessionTrack) GetExplicit() OptNilBool {
	return s.Explicit
}

// SetID sets the value of ID.
func (s *SessionTrack) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SessionTrack) SetName(val string) {
	s.Name = val
}

// SetArtists sets the value of Artists.
func (s *SessionTrack) SetArtists(val []uuid.UUID) {
	s.Artists = val
}

// SetAlbum sets the value of Album.
func (s *SessionTrack) SetAlbum(val OptNilUUID) {
	s.Album = val
}

// SetExplicit sets the value of Explicit.
func (s *SessionTrack) SetExplicit(val OptNilBool) {
	s.Explicit = val
}

// Ref: #/components/schemas/SessionsResponse
type SessionsResponse struct {
	// Days containing sessions, ordered newest first.
	Days []SessionDay `json:"days"`
	// Deduplicated track metadata referenced by sessions.
	Tracks []SessionTrack `json:"tracks"`
	// Deduplicated album metadata referenced by sessions.
	Albums []SessionAlbum `json:"albums"`
	// Deduplicated artist metadata referenced by sessions.
	Artists []SessionArtist `json:"artists"`
}

// GetDays returns the value of Days.
func (s *SessionsResponse) GetDays() []SessionDay {
	return s.Days
}

// GetTracks returns the value of Tracks.
func (s *SessionsResponse) GetTracks() []SessionTrack {
	return s.Tracks
}

// GetAlbums returns the value of Albums.
func (s *SessionsResponse) GetAlbums() []SessionAlbum {
	return s.Albums
}

// GetArtists returns the value of Artists.
func (s *SessionsResponse) GetArtists() []SessionArtist {
	return s.Artists
}

// SetDays sets the value of Days.
func (s *SessionsResponse) SetDays(val []SessionDay) {
	s.Days = val
}

// SetTracks sets the value of Tracks.
func (s *SessionsResponse) SetTracks(val []SessionTrack) {
	s.Tracks = val
}

// SetAlbums sets the value of Albums.
func (s *SessionsResponse) SetAlbums(val []SessionAlbum) {
	s.Albums = val
}

// SetArtists sets the value of Artists.
func (s *SessionsResponse) SetArtists(val []SessionArtist) {
	s.Artists = val
}

func (*SessionsResponse) getListenSessionsRes()     {}
func (*SessionsResponse) getUserListenSessionsRes() {}

type SetActivityApplicationJSONBadRequest ErrorResponse

func (*SetActivityApplicationJSONBadRequest) setActivityRes() {}

type SetActivityApplicationJSONInternalServerError ErrorResponse

func (*SetActivityApplicationJSONInternalServerError) setActivityRes() {}

type SetActivityApplicationJSONUnauthorized ErrorResponse

func (*SetActivityApplicationJSONUnauthorized) setActivityRes() {}

// Ref: #/components/schemas/SetActivityItem
type SetActivityItem struct {
	// Unique identifier for the listening session, typically a UUID or random string used to group
	// related activities.
	SessionID string `json:"session_id"`
	// UUID of the track being played.
	TrackID uuid.UUID `json:"track_id"`
	// Whether the user is currently playing this track (true) or has stopped/paused (false).
	Active bool `json:"active"`
	// Current playback position in seconds from the start of the track.
	Position int64 `json:"position"`
	// ISO 8601 timestamp when playback of this track started.
	StartTimestamp OptDateTime `json:"start_timestamp"`
	// ISO 8601 timestamp when playback of this track is expected to end (for background playback
	// estimation).
	EndTimestamp OptDateTime `json:"end_timestamp"`
}

// GetSessionID returns the value of SessionID.
func (s *SetActivityItem) GetSessionID() string {
	return s.SessionID
}

// GetTrackID returns the value of TrackID.
func (s *SetActivityItem) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetActive returns the value of Active.
func (s *SetActivityItem) GetActive() bool {
	return s.Active
}

// GetPosition returns the value of Position.
func (s *SetActivityItem) GetPosition() int64 {
	return s.Position
}

// GetStartTimestamp returns the value of StartTimestamp.
func (s *SetActivityItem) GetStartTimestamp() OptDateTime {
	return s.StartTimestamp
}

// GetEndTimestamp returns the value of EndTimestamp.
func (s *SetActivityItem) GetEndTimestamp() OptDateTime {
	return s.EndTimestamp
}

// SetSessionID sets the value of SessionID.
func (s *SetActivityItem) SetSessionID(val string) {
	s.SessionID = val
}

// SetTrackID sets the value of TrackID.
func (s *SetActivityItem) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetActive sets the value of Active.
func (s *SetActivityItem) SetActive(val bool) {
	s.Active = val
}

// SetPosition sets the value of Position.
func (s *SetActivityItem) SetPosition(val int64) {
	s.Position = val
}

// SetStartTimestamp sets the value of StartTimestamp.
func (s *SetActivityItem) SetStartTimestamp(val OptDateTime) {
	s.StartTimestamp = val
}

// SetEndTimestamp sets the value of EndTimestamp.
func (s *SetActivityItem) SetEndTimestamp(val OptDateTime) {
	s.EndTimestamp = val
}

type SetBestFriendApplicationJSONBadRequest ErrorResponse

func (*SetBestFriendApplicationJSONBadRequest) setBestFriendRes() {}

type SetBestFriendApplicationJSONForbidden ErrorResponse

func (*SetBestFriendApplicationJSONForbidden) setBestFriendRes() {}

type SetBestFriendApplicationJSONInternalServerError ErrorResponse

func (*SetBestFriendApplicationJSONInternalServerError) setBestFriendRes() {}

type SetBestFriendApplicationJSONUnauthorized ErrorResponse

func (*SetBestFriendApplicationJSONUnauthorized) setBestFriendRes() {}

type SetBlockedApplicationJSONBadRequest ErrorResponse

func (*SetBlockedApplicationJSONBadRequest) setBlockedRes() {}

type SetBlockedApplicationJSONForbidden ErrorResponse

func (*SetBlockedApplicationJSONForbidden) setBlockedRes() {}

type SetBlockedApplicationJSONInternalServerError ErrorResponse

func (*SetBlockedApplicationJSONInternalServerError) setBlockedRes() {}

type SetBlockedApplicationJSONUnauthorized ErrorResponse

func (*SetBlockedApplicationJSONUnauthorized) setBlockedRes() {}

type SignInApplicationJSONBadRequest ErrorResponse

func (*SignInApplicationJSONBadRequest) signInRes() {}

type SignInApplicationJSONInternalServerError ErrorResponse

func (*SignInApplicationJSONInternalServerError) signInRes() {}

// SignInOK is response for SignIn operation.
type SignInOK struct {
	HxLocation OptString
}

// GetHxLocation returns the value of HxLocation.
func (s *SignInOK) GetHxLocation() OptString {
	return s.HxLocation
}

// SetHxLocation sets the value of HxLocation.
func (s *SignInOK) SetHxLocation(val OptString) {
	s.HxLocation = val
}

func (*SignInOK) signInRes() {}

// Ref: #/components/schemas/SignInRequest
type SignInRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *SignInRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *SignInRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *SignInRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *SignInRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/Track
type Track struct {
	TrackID         uuid.UUID      `json:"track_id"`
	UserID          OptNilUUID     `json:"user_id"`
	Name            string         `json:"name"`
	Seconds         OptNilUint16   `json:"seconds"`
	Lyrics          OptNilString   `json:"lyrics"`
	Explicit        OptNilBool     `json:"explicit"`
	MusicbrainzID   OptNilUUID     `json:"musicbrainz_id"`
	SpotifyURL      OptNilString   `json:"spotify_url"`
	AppleMusicURL   OptNilString   `json:"apple_music_url"`
	TidalURL        OptNilString   `json:"tidal_url"`
	YoutubeMusicURL OptNilString   `json:"youtube_music_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       OptNilDateTime `json:"updated_at"`
}

// GetTrackID returns the value of TrackID.
func (s *Track) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetUserID returns the value of UserID.
func (s *Track) GetUserID() OptNilUUID {
	return s.UserID
}

// GetName returns the value of Name.
func (s *Track) GetName() string {
	return s.Name
}

// GetSeconds returns the value of Seconds.
func (s *Track) GetSeconds() OptNilUint16 {
	return s.Seconds
}

// GetLyrics returns the value of Lyrics.
func (s *Track) GetLyrics() OptNilString {
	return s.Lyrics
}

// GetExplicit returns the value of Explicit.
func (s *Track) GetExplicit() OptNilBool {
	return s.Explicit
}

// GetMusicbrainzID returns the value of MusicbrainzID.
func (s *Track) GetMusicbrainzID() OptNilUUID {
	return s.MusicbrainzID
}

// GetSpotifyURL returns the value of SpotifyURL.
func (s *Track) GetSpotifyURL() OptNilString {
	return s.SpotifyURL
}

// GetAppleMusicURL returns the value of AppleMusicURL.
func (s *Track) GetAppleMusicURL() OptNilString {
	return s.AppleMusicURL
}

// GetTidalURL returns the value of TidalURL.
func (s *Track) GetTidalURL() OptNilString {
	return s.TidalURL
}

// GetYoutubeMusicURL returns the value of YoutubeMusicURL.
func (s *Track) GetYoutubeMusicURL() OptNilString {
	return s.YoutubeMusicURL
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Track) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Track) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetTrackID sets the value of TrackID.
func (s *Track) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetUserID sets the value of UserID.
func (s *Track) SetUserID(val OptNilUUID) {
	s.UserID = val
}

// SetName sets the value of Name.
func (s *Track) SetName(val string) {
	s.Name = val
}

// SetSeconds sets the value of Seconds.
func (s *Track) SetSeconds(val OptNilUint16) {
	s.Seconds = val
}

// SetLyrics sets the value of Lyrics.
func (s *Track) SetLyrics(val OptNilString) {
	s.Lyrics = val
}

// SetExplicit sets the value of Explicit.
func (s *Track) SetExplicit(val OptNilBool) {
	s.Explicit = val
}

// SetMusicbrainzID sets the value of MusicbrainzID.
func (s *Track) SetMusicbrainzID(val OptNilUUID) {
	s.MusicbrainzID = val
}

// SetSpotifyURL sets the value of SpotifyURL.
func (s *Track) SetSpotifyURL(val OptNilString) {
	s.SpotifyURL = val
}

// SetAppleMusicURL sets the value of AppleMusicURL.
func (s *Track) SetAppleMusicURL(val OptNilString) {
	s.AppleMusicURL = val
}

// SetTidalURL sets the value of TidalURL.
func (s *Track) SetTidalURL(val OptNilString) {
	s.TidalURL = val
}

// SetYoutubeMusicURL sets the value of YoutubeMusicURL.
func (s *Track) SetYoutubeMusicURL(val OptNilString) {
	s.YoutubeMusicURL = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Track) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Track) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

func (*Track) getTrackRes() {}

// Ref: #/components/schemas/TrackArtist
type TrackArtist struct {
	TrackID  uuid.UUID `json:"track_id"`
	ArtistID uuid.UUID `json:"artist_id"`
}

// GetTrackID returns the value of TrackID.
func (s *TrackArtist) GetTrackID() uuid.UUID {
	return s.TrackID
}

// GetArtistID returns the value of ArtistID.
func (s *TrackArtist) GetArtistID() uuid.UUID {
	return s.ArtistID
}

// SetTrackID sets the value of TrackID.
func (s *TrackArtist) SetTrackID(val uuid.UUID) {
	s.TrackID = val
}

// SetArtistID sets the value of ArtistID.
func (s *TrackArtist) SetArtistID(val uuid.UUID) {
	s.ArtistID = val
}

type UnauthorizedTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s UnauthorizedTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*UnauthorizedTextPlain) addFriendRes()              {}
func (*UnauthorizedTextPlain) addToLibraryRes()           {}
func (*UnauthorizedTextPlain) getAlbumRes()               {}
func (*UnauthorizedTextPlain) getArtistRes()              {}
func (*UnauthorizedTextPlain) getLibraryMetadataRes()     {}
func (*UnauthorizedTextPlain) getListenSessionsRes()      {}
func (*UnauthorizedTextPlain) getRelationsRes()           {}
func (*UnauthorizedTextPlain) getTrackRes()               {}
func (*UnauthorizedTextPlain) getUserDetailsRes()         {}
func (*UnauthorizedTextPlain) getUserListenSessionsRes()  {}
func (*UnauthorizedTextPlain) joinFreeBetaRes()           {}
func (*UnauthorizedTextPlain) removeFriendRes()           {}
func (*UnauthorizedTextPlain) removeFromLibraryRes()      {}
func (*UnauthorizedTextPlain) searchTracksViaDetailsRes() {}
func (*UnauthorizedTextPlain) setActivityRes()            {}
func (*UnauthorizedTextPlain) setBestFriendRes()          {}
func (*UnauthorizedTextPlain) setBlockedRes()             {}
func (*UnauthorizedTextPlain) updateLibraryRes()          {}
func (*UnauthorizedTextPlain) updateUserRes()             {}
func (*UnauthorizedTextPlain) validateTokenRes()          {}

type UpdateLibraryApplicationJSONBadRequest ErrorResponse

func (*UpdateLibraryApplicationJSONBadRequest) updateLibraryRes() {}

type UpdateLibraryApplicationJSONInternalServerError ErrorResponse

func (*UpdateLibraryApplicationJSONInternalServerError) updateLibraryRes() {}

type UpdateLibraryApplicationJSONUnauthorized ErrorResponse

func (*UpdateLibraryApplicationJSONUnauthorized) updateLibraryRes() {}

type UpdateUserApplicationJSONBadRequest ErrorResponse

func (*UpdateUserApplicationJSONBadRequest) updateUserRes() {}

type UpdateUserApplicationJSONInternalServerError ErrorResponse

func (*UpdateUserApplicationJSONInternalServerError) updateUserRes() {}

type UpdateUserApplicationJSONUnauthorized ErrorResponse

func (*UpdateUserApplicationJSONUnauthorized) updateUserRes() {}

// Ref: #/components/schemas/UpdateUserRequest
type UpdateUserRequest struct {
	Handle     OptNilString      `json:"handle"`
	Name       OptNilString      `json:"name"`
	Email      OptNilString      `json:"email"`
	Password   OptNilString      `json:"password"`
	Visibility OptUserVisibility `json:"visibility"`
}

// GetHandle returns the value of Handle.
func (s *UpdateUserRequest) GetHandle() OptNilString {
	return s.Handle
}

// GetName returns the value of Name.
func (s *UpdateUserRequest) GetName() OptNilString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *UpdateUserRequest) GetEmail() OptNilString {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *UpdateUserRequest) GetPassword() OptNilString {
	return s.Password
}

// GetVisibility returns the value of Visibility.
func (s *UpdateUserRequest) GetVisibility() OptUserVisibility {
	return s.Visibility
}

// SetHandle sets the value of Handle.
func (s *UpdateUserRequest) SetHandle(val OptNilString) {
	s.Handle = val
}

// SetName sets the value of Name.
func (s *UpdateUserRequest) SetName(val OptNilString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *UpdateUserRequest) SetEmail(val OptNilString) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *UpdateUserRequest) SetPassword(val OptNilString) {
	s.Password = val
}

// SetVisibility sets the value of Visibility.
func (s *UpdateUserRequest) SetVisibility(val OptUserVisibility) {
	s.Visibility = val
}

// Ref: #/components/schemas/User
type User struct {
	UserID                 uuid.UUID      `json:"user_id"`
	Handle                 string         `json:"handle"`
	Name                   string         `json:"name"`
	Email                  string         `json:"email"`
	Visibility             UserVisibility `json:"visibility"`
	SubscriptionExpiration time.Time      `json:"subscription_expiration"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              OptNilDateTime `json:"updated_at"`
}

// GetUserID returns the value of UserID.
func (s *User) GetUserID() uuid.UUID {
	return s.UserID
}

// GetHandle returns the value of Handle.
func (s *User) GetHandle() string {
	return s.Handle
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// GetVisibility returns the value of Visibility.
func (s *User) GetVisibility() UserVisibility {
	return s.Visibility
}

// GetSubscriptionExpiration returns the value of SubscriptionExpiration.
func (s *User) GetSubscriptionExpiration() time.Time {
	return s.SubscriptionExpiration
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *User) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetUserID sets the value of UserID.
func (s *User) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetHandle sets the value of Handle.
func (s *User) SetHandle(val string) {
	s.Handle = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}

// SetVisibility sets the value of Visibility.
func (s *User) SetVisibility(val UserVisibility) {
	s.Visibility = val
}

// SetSubscriptionExpiration sets the value of SubscriptionExpiration.
func (s *User) SetSubscriptionExpiration(val time.Time) {
	s.SubscriptionExpiration = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *User) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

func (*User) getUserDetailsRes() {}

// 0=Friend: users are friends
// 1=BestFriend: source user set target user as a best friend
// 2=OutgoingRequest: source user has an outgoing friend request
// 3=IncomingRequest: source user has an incoming friend request
// 4=BlockSent: source user has blocked target user
// 5=BlockReceived: target user has blocked source user.
// Ref: #/components/schemas/UserRelation
type UserRelation uint8

const (
	UserRelation0 UserRelation = 0
	UserRelation1 UserRelation = 1
	UserRelation2 UserRelation = 2
	UserRelation3 UserRelation = 3
	UserRelation4 UserRelation = 4
	UserRelation5 UserRelation = 5
)

// AllValues returns all UserRelation values.
func (UserRelation) AllValues() []UserRelation {
	return []UserRelation{
		UserRelation0,
		UserRelation1,
		UserRelation2,
		UserRelation3,
		UserRelation4,
		UserRelation5,
	}
}

// 0=Public: visible to everyone
// 1=Friends: visible to the user's friends
// 1=BestFriends: visible to the user's best friends
// 1=Private: visible to only the user.
// Ref: #/components/schemas/UserVisibility
type UserVisibility uint8

const (
	UserVisibility0 UserVisibility = 0
	UserVisibility1 UserVisibility = 1
	UserVisibility2 UserVisibility = 2
	UserVisibility3 UserVisibility = 3
)

// AllValues returns all UserVisibility values.
func (UserVisibility) AllValues() []UserVisibility {
	return []UserVisibility{
		UserVisibility0,
		UserVisibility1,
		UserVisibility2,
		UserVisibility3,
	}
}
