// Code generated by ogen, DO NOT EDIT.
package openapi

type AddFriendRes interface {
	addFriendRes()
}

type AddToLibraryRes interface {
	addToLibraryRes()
}

type GetAlbumRes interface {
	getAlbumRes()
}

type GetArtistRes interface {
	getArtistRes()
}

type GetCalendarListensRes interface {
	getCalendarListensRes()
}

type GetFriendsRes interface {
	getFriendsRes()
}

type GetLibraryMetadataRes interface {
	getLibraryMetadataRes()
}

type GetListenSessionsRes interface {
	getListenSessionsRes()
}

type GetRelationsRes interface {
	getRelationsRes()
}

type GetTrackRes interface {
	getTrackRes()
}

type GetUserDetailsRes interface {
	getUserDetailsRes()
}

type GetUserListenSessionsRes interface {
	getUserListenSessionsRes()
}

type JoinFreeBetaRes interface {
	joinFreeBetaRes()
}

type RegisterRes interface {
	registerRes()
}

type RemoveFriendRes interface {
	removeFriendRes()
}

type RemoveFromLibraryRes interface {
	removeFromLibraryRes()
}

type SearchTracksViaDetailsRes interface {
	searchTracksViaDetailsRes()
}

type SetActivityRes interface {
	setActivityRes()
}

type SetBestFriendRes interface {
	setBestFriendRes()
}

type SetBlockedRes interface {
	setBlockedRes()
}

type SignInRes interface {
	signInRes()
}

type UpdateLibraryRes interface {
	updateLibraryRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type ValidateTokenRes interface {
	validateTokenRes()
}
