// Code generated by ogen, DO NOT EDIT.

package openapi

// setDefaults set default value of fields.
func (s *LibraryAddEntity) setDefaults() {
	{
		val := bool(false)
		s.ForceAdd.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *LibraryUpdateRequest) setDefaults() {
	{
		val := bool(false)
		s.AppendTrackArtists.SetTo(val)
	}
	{
		val := bool(false)
		s.AppendAlbumArtists.SetTo(val)
	}
	{
		val := bool(false)
		s.AppendAlbumTracks.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ListensSessionsRequest) setDefaults() {
	{
		val := int64(1000)
		s.Limit.SetTo(val)
	}
}
