// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn48AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn1AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn36AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn9AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
	}
	rn13AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn4AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
	}
	rn5AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn15AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
	}
	rn12AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn59AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn69AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn33AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn57AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn58AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn61AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn63AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn65AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn67AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn68AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn25AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn27AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn29AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn50AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn52AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn70AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [3]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'p': // Prefix: "pi/"

					if l := len("pi/"); len(elem) >= l && elem[0:l] == "pi/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '@': // Prefix: "@"
						origElem := elem
						if l := len("@"); len(elem) >= l && elem[0:l] == "@" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "handle"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/listens/sessions"

							if l := len("/listens/sessions"); len(elem) >= l && elem[0:l] == "/listens/sessions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleGetUserListenSessionsRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn48AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 'a': // Prefix: "a"
						origElem := elem
						if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "dd-friend"

							if l := len("dd-friend"); len(elem) >= l && elem[0:l] == "dd-friend" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleAddFriendRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn1AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'l': // Prefix: "lbums/"

							if l := len("lbums/"); len(elem) >= l && elem[0:l] == "lbums/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetAlbumRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'r': // Prefix: "rtists/"

							if l := len("rtists/"); len(elem) >= l && elem[0:l] == "rtists/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetArtistRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 'c': // Prefix: "conversations/"
						origElem := elem
						if l := len("conversations/"); len(elem) >= l && elem[0:l] == "conversations/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "conversation_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/messages"

							if l := len("/messages"); len(elem) >= l && elem[0:l] == "/messages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleGetMessagesRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleSendMessageRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn36AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "message_id"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch r.Method {
									case "DELETE":
										s.handleDeleteMessageRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "PATCH":
										s.handleEditMessageRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,PATCH",
											allowedHeaders: rn9AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "application/json",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'r': // Prefix: "rea"

										if l := len("rea"); len(elem) >= l && elem[0:l] == "rea" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'c': // Prefix: "ctions/"

											if l := len("ctions/"); len(elem) >= l && elem[0:l] == "ctions/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "emoji"
											// Leaf parameter, slashes are prohibited
											idx := strings.IndexByte(elem, '/')
											if idx >= 0 {
												break
											}
											args[2] = elem
											elem = ""

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "DELETE":
													s.handleDeleteMessageReactionRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												case "PUT":
													s.handleAddMessageReactionRequest([3]string{
														args[0],
														args[1],
														args[2],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "DELETE,PUT",
														allowedHeaders: nil,
														acceptPost:     "",
														acceptPatch:    "",
													})
												}

												return
											}

										case 'd': // Prefix: "d"

											if l := len("d"); len(elem) >= l && elem[0:l] == "d" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handleReadMessageRequest([2]string{
														args[0],
														args[1],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "POST",
														allowedHeaders: nil,
														acceptPost:     "",
														acceptPatch:    "",
													})
												}

												return
											}

										}

									case 't': // Prefix: "thread"

										if l := len("thread"); len(elem) >= l && elem[0:l] == "thread" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "GET":
												s.handleGetMessageThreadRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "GET",
													allowedHeaders: nil,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							}

						}

						elem = origElem
					case 'g': // Prefix: "groups"
						origElem := elem
						if l := len("groups"); len(elem) >= l && elem[0:l] == "groups" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleGetGroupsRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateGroupRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST",
									allowedHeaders: rn13AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "group_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "DELETE":
									s.handleDeleteGroupRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleGetGroupRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PATCH":
									s.handleEditGroupRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,GET,PATCH",
										allowedHeaders: rn4AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/roles"

								if l := len("/roles"); len(elem) >= l && elem[0:l] == "/roles" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleGetGroupRolesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleAddGroupRolesRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn5AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "user_id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "DELETE":
											s.handleDeleteGroupRoleRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										case "PATCH":
											s.handleUpdateGroupRolesRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE,PATCH",
												allowedHeaders: rn15AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "application/json",
											})
										}

										return
									}

								}

							}

						}

						elem = origElem
					case 'j': // Prefix: "join-free-beta"
						origElem := elem
						if l := len("join-free-beta"); len(elem) >= l && elem[0:l] == "join-free-beta" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleJoinFreeBetaRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

						elem = origElem
					case 'l': // Prefix: "li"
						origElem := elem
						if l := len("li"); len(elem) >= l && elem[0:l] == "li" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'b': // Prefix: "brary/"

							if l := len("brary/"); len(elem) >= l && elem[0:l] == "brary/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "add"

								if l := len("add"); len(elem) >= l && elem[0:l] == "add" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleAddToLibraryRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn12AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'g': // Prefix: "get-metadata"

								if l := len("get-metadata"); len(elem) >= l && elem[0:l] == "get-metadata" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetLibraryMetadataRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'r': // Prefix: "remove"

								if l := len("remove"); len(elem) >= l && elem[0:l] == "remove" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleRemoveFromLibraryRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn59AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'u': // Prefix: "update"

								if l := len("update"); len(elem) >= l && elem[0:l] == "update" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleUpdateLibraryRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn69AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 's': // Prefix: "stens/sessions"

							if l := len("stens/sessions"); len(elem) >= l && elem[0:l] == "stens/sessions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleGetListenSessionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn33AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 'r': // Prefix: "re"
						origElem := elem
						if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "gister"

							if l := len("gister"); len(elem) >= l && elem[0:l] == "gister" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleRegisterRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn57AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'l': // Prefix: "lations"

							if l := len("lations"); len(elem) >= l && elem[0:l] == "lations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleGetRelationsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/details"

								if l := len("/details"); len(elem) >= l && elem[0:l] == "/details" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetRelationsDetailsRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'm': // Prefix: "move-friend"

							if l := len("move-friend"); len(elem) >= l && elem[0:l] == "move-friend" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleRemoveFriendRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn58AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 's': // Prefix: "s"
						origElem := elem
						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "e"

							if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "arch-tracks-via-details"

								if l := len("arch-tracks-via-details"); len(elem) >= l && elem[0:l] == "arch-tracks-via-details" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleSearchTracksViaDetailsRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn61AllowedHeaders,
											acceptPost:     "application/json",
											acceptPatch:    "",
										})
									}

									return
								}

							case 't': // Prefix: "t-"

								if l := len("t-"); len(elem) >= l && elem[0:l] == "t-" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "activity"

									if l := len("activity"); len(elem) >= l && elem[0:l] == "activity" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleSetActivityRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn63AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'b': // Prefix: "b"

									if l := len("b"); len(elem) >= l && elem[0:l] == "b" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'e': // Prefix: "est-friend"

										if l := len("est-friend"); len(elem) >= l && elem[0:l] == "est-friend" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleSetBestFriendRequest([0]string{}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn65AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}

									case 'l': // Prefix: "locked"

										if l := len("locked"); len(elem) >= l && elem[0:l] == "locked" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleSetBlockedRequest([0]string{}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn67AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								}

							}

						case 'i': // Prefix: "ignin"

							if l := len("ignin"); len(elem) >= l && elem[0:l] == "ignin" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleSignInRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn68AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 't': // Prefix: "tatistics/"

							if l := len("tatistics/"); len(elem) >= l && elem[0:l] == "tatistics/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'g': // Prefix: "global/top/"

								if l := len("global/top/"); len(elem) >= l && elem[0:l] == "global/top/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "a"

									if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'l': // Prefix: "lbums"

										if l := len("lbums"); len(elem) >= l && elem[0:l] == "lbums" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleGetGlobalTopAlbumsRequest([0]string{}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn25AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}

									case 'r': // Prefix: "rtists"

										if l := len("rtists"); len(elem) >= l && elem[0:l] == "rtists" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "POST":
												s.handleGetGlobalTopArtistsRequest([0]string{}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "POST",
													allowedHeaders: rn27AllowedHeaders,
													acceptPost:     "application/json",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								case 't': // Prefix: "tracks"

									if l := len("tracks"); len(elem) >= l && elem[0:l] == "tracks" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleGetGlobalTopTracksRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn29AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							case 'u': // Prefix: "user/"

								if l := len("user/"); len(elem) >= l && elem[0:l] == "user/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'l': // Prefix: "listens/days"

									if l := len("listens/days"); len(elem) >= l && elem[0:l] == "listens/days" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleGetUserListensByDaysRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn50AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								case 't': // Prefix: "top/artist-plays"

									if l := len("top/artist-plays"); len(elem) >= l && elem[0:l] == "top/artist-plays" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleGetUserTopArtistPlayStatsRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn52AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

						elem = origElem
					case 't': // Prefix: "tracks/"
						origElem := elem
						if l := len("tracks/"); len(elem) >= l && elem[0:l] == "tracks/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetTrackRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

						elem = origElem
					case 'u': // Prefix: "user/"
						origElem := elem
						if l := len("user/"); len(elem) >= l && elem[0:l] == "user/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "details"

							if l := len("details"); len(elem) >= l && elem[0:l] == "details" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetUserDetailsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'i': // Prefix: "integrations"

							if l := len("integrations"); len(elem) >= l && elem[0:l] == "integrations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetUserIntegrationsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'u': // Prefix: "update"

							if l := len("update"); len(elem) >= l && elem[0:l] == "update" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleUpdateUserRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn70AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						}

						elem = origElem
					case 'v': // Prefix: "validate"
						origElem := elem
						if l := len("validate"); len(elem) >= l && elem[0:l] == "validate" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleValidateTokenRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

						elem = origElem
					}
					// Param: "user_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/calendar/listens"

						if l := len("/calendar/listens"); len(elem) >= l && elem[0:l] == "/calendar/listens" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleGetCalendarListensRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 's': // Prefix: "syncapi.yaml"

					if l := len("syncapi.yaml"); len(elem) >= l && elem[0:l] == "syncapi.yaml" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetAsyncAPIRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'o': // Prefix: "openapi.yaml"

				if l := len("openapi.yaml"); len(elem) >= l && elem[0:l] == "openapi.yaml" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetOpenAPIRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [3]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"

				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'p': // Prefix: "pi/"

					if l := len("pi/"); len(elem) >= l && elem[0:l] == "pi/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '@': // Prefix: "@"
						origElem := elem
						if l := len("@"); len(elem) >= l && elem[0:l] == "@" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "handle"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/listens/sessions"

							if l := len("/listens/sessions"); len(elem) >= l && elem[0:l] == "/listens/sessions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = GetUserListenSessionsOperation
									r.summary = "Get listen sessions for another user"
									r.operationID = "getUserListenSessions"
									r.operationGroup = ""
									r.pathPattern = "/api/@{handle}/listens/sessions"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 'a': // Prefix: "a"
						origElem := elem
						if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "dd-friend"

							if l := len("dd-friend"); len(elem) >= l && elem[0:l] == "dd-friend" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = AddFriendOperation
									r.summary = "Add a friend"
									r.operationID = "addFriend"
									r.operationGroup = ""
									r.pathPattern = "/api/add-friend"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'l': // Prefix: "lbums/"

							if l := len("lbums/"); len(elem) >= l && elem[0:l] == "lbums/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetAlbumOperation
									r.summary = "Get album details"
									r.operationID = "getAlbum"
									r.operationGroup = ""
									r.pathPattern = "/api/albums/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'r': // Prefix: "rtists/"

							if l := len("rtists/"); len(elem) >= l && elem[0:l] == "rtists/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetArtistOperation
									r.summary = "Get artist details"
									r.operationID = "getArtist"
									r.operationGroup = ""
									r.pathPattern = "/api/artists/{id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 'c': // Prefix: "conversations/"
						origElem := elem
						if l := len("conversations/"); len(elem) >= l && elem[0:l] == "conversations/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "conversation_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/messages"

							if l := len("/messages"); len(elem) >= l && elem[0:l] == "/messages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = GetMessagesOperation
									r.summary = "Get conversation messages."
									r.operationID = "getMessages"
									r.operationGroup = ""
									r.pathPattern = "/api/conversations/{conversation_id}/messages"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = SendMessageOperation
									r.summary = "Send a conversation message."
									r.operationID = "sendMessage"
									r.operationGroup = ""
									r.pathPattern = "/api/conversations/{conversation_id}/messages"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "message_id"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[1] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									switch method {
									case "DELETE":
										r.name = DeleteMessageOperation
										r.summary = "Delete a message."
										r.operationID = "deleteMessage"
										r.operationGroup = ""
										r.pathPattern = "/api/conversations/{conversation_id}/messages/{message_id}"
										r.args = args
										r.count = 2
										return r, true
									case "PATCH":
										r.name = EditMessageOperation
										r.summary = "Edit a message."
										r.operationID = "editMessage"
										r.operationGroup = ""
										r.pathPattern = "/api/conversations/{conversation_id}/messages/{message_id}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'r': // Prefix: "rea"

										if l := len("rea"); len(elem) >= l && elem[0:l] == "rea" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'c': // Prefix: "ctions/"

											if l := len("ctions/"); len(elem) >= l && elem[0:l] == "ctions/" {
												elem = elem[l:]
											} else {
												break
											}

											// Param: "emoji"
											// Leaf parameter, slashes are prohibited
											idx := strings.IndexByte(elem, '/')
											if idx >= 0 {
												break
											}
											args[2] = elem
											elem = ""

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "DELETE":
													r.name = DeleteMessageReactionOperation
													r.summary = "Remove a reaction from a message."
													r.operationID = "deleteMessageReaction"
													r.operationGroup = ""
													r.pathPattern = "/api/conversations/{conversation_id}/messages/{message_id}/reactions/{emoji}"
													r.args = args
													r.count = 3
													return r, true
												case "PUT":
													r.name = AddMessageReactionOperation
													r.summary = "Add a reaction to a message."
													r.operationID = "addMessageReaction"
													r.operationGroup = ""
													r.pathPattern = "/api/conversations/{conversation_id}/messages/{message_id}/reactions/{emoji}"
													r.args = args
													r.count = 3
													return r, true
												default:
													return
												}
											}

										case 'd': // Prefix: "d"

											if l := len("d"); len(elem) >= l && elem[0:l] == "d" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = ReadMessageOperation
													r.summary = "Read a message."
													r.operationID = "readMessage"
													r.operationGroup = ""
													r.pathPattern = "/api/conversations/{conversation_id}/messages/{message_id}/read"
													r.args = args
													r.count = 2
													return r, true
												default:
													return
												}
											}

										}

									case 't': // Prefix: "thread"

										if l := len("thread"); len(elem) >= l && elem[0:l] == "thread" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "GET":
												r.name = GetMessageThreadOperation
												r.summary = "Get message thread."
												r.operationID = "getMessageThread"
												r.operationGroup = ""
												r.pathPattern = "/api/conversations/{conversation_id}/messages/{message_id}/thread"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								}

							}

						}

						elem = origElem
					case 'g': // Prefix: "groups"
						origElem := elem
						if l := len("groups"); len(elem) >= l && elem[0:l] == "groups" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = GetGroupsOperation
								r.summary = "Get groups visible to the user."
								r.operationID = "getGroups"
								r.operationGroup = ""
								r.pathPattern = "/api/groups"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = CreateGroupOperation
								r.summary = "Create a new group as owner."
								r.operationID = "createGroup"
								r.operationGroup = ""
								r.pathPattern = "/api/groups"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "group_id"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "DELETE":
									r.name = DeleteGroupOperation
									r.summary = "Delete a group if owned by the user."
									r.operationID = "deleteGroup"
									r.operationGroup = ""
									r.pathPattern = "/api/groups/{group_id}"
									r.args = args
									r.count = 1
									return r, true
								case "GET":
									r.name = GetGroupOperation
									r.summary = "Get group."
									r.operationID = "getGroup"
									r.operationGroup = ""
									r.pathPattern = "/api/groups/{group_id}"
									r.args = args
									r.count = 1
									return r, true
								case "PATCH":
									r.name = EditGroupOperation
									r.summary = "Edit a group."
									r.operationID = "editGroup"
									r.operationGroup = ""
									r.pathPattern = "/api/groups/{group_id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/roles"

								if l := len("/roles"); len(elem) >= l && elem[0:l] == "/roles" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = GetGroupRolesOperation
										r.summary = "Get group roles."
										r.operationID = "getGroupRoles"
										r.operationGroup = ""
										r.pathPattern = "/api/groups/{group_id}/roles"
										r.args = args
										r.count = 1
										return r, true
									case "POST":
										r.name = AddGroupRolesOperation
										r.summary = "Add group roles."
										r.operationID = "AddGroupRoles"
										r.operationGroup = ""
										r.pathPattern = "/api/groups/{group_id}/roles"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "user_id"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "DELETE":
											r.name = DeleteGroupRoleOperation
											r.summary = "Remove a user from a group."
											r.operationID = "deleteGroupRole"
											r.operationGroup = ""
											r.pathPattern = "/api/groups/{group_id}/roles/{user_id}"
											r.args = args
											r.count = 2
											return r, true
										case "PATCH":
											r.name = UpdateGroupRolesOperation
											r.summary = "Update group roles."
											r.operationID = "UpdateGroupRoles"
											r.operationGroup = ""
											r.pathPattern = "/api/groups/{group_id}/roles/{user_id}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						}

						elem = origElem
					case 'j': // Prefix: "join-free-beta"
						origElem := elem
						if l := len("join-free-beta"); len(elem) >= l && elem[0:l] == "join-free-beta" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = JoinFreeBetaOperation
								r.summary = "Join free beta"
								r.operationID = "joinFreeBeta"
								r.operationGroup = ""
								r.pathPattern = "/api/join-free-beta"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					case 'l': // Prefix: "li"
						origElem := elem
						if l := len("li"); len(elem) >= l && elem[0:l] == "li" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'b': // Prefix: "brary/"

							if l := len("brary/"); len(elem) >= l && elem[0:l] == "brary/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "add"

								if l := len("add"); len(elem) >= l && elem[0:l] == "add" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = AddToLibraryOperation
										r.summary = "Add items to library"
										r.operationID = "addToLibrary"
										r.operationGroup = ""
										r.pathPattern = "/api/library/add"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'g': // Prefix: "get-metadata"

								if l := len("get-metadata"); len(elem) >= l && elem[0:l] == "get-metadata" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetLibraryMetadataOperation
										r.summary = "Get library metadata"
										r.operationID = "getLibraryMetadata"
										r.operationGroup = ""
										r.pathPattern = "/api/library/get-metadata"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'r': // Prefix: "remove"

								if l := len("remove"); len(elem) >= l && elem[0:l] == "remove" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = RemoveFromLibraryOperation
										r.summary = "Remove items from library"
										r.operationID = "removeFromLibrary"
										r.operationGroup = ""
										r.pathPattern = "/api/library/remove"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'u': // Prefix: "update"

								if l := len("update"); len(elem) >= l && elem[0:l] == "update" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = UpdateLibraryOperation
										r.summary = "Update items in library"
										r.operationID = "updateLibrary"
										r.operationGroup = ""
										r.pathPattern = "/api/library/update"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							}

						case 's': // Prefix: "stens/sessions"

							if l := len("stens/sessions"); len(elem) >= l && elem[0:l] == "stens/sessions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = GetListenSessionsOperation
									r.summary = "Get recent listening sessions"
									r.operationID = "getListenSessions"
									r.operationGroup = ""
									r.pathPattern = "/api/listens/sessions"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 'r': // Prefix: "re"
						origElem := elem
						if l := len("re"); len(elem) >= l && elem[0:l] == "re" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'g': // Prefix: "gister"

							if l := len("gister"); len(elem) >= l && elem[0:l] == "gister" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = RegisterOperation
									r.summary = "Register a new user"
									r.operationID = "register"
									r.operationGroup = ""
									r.pathPattern = "/api/register"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'l': // Prefix: "lations"

							if l := len("lations"); len(elem) >= l && elem[0:l] == "lations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = GetRelationsOperation
									r.summary = "Get user relations"
									r.operationID = "getRelations"
									r.operationGroup = ""
									r.pathPattern = "/api/relations"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/details"

								if l := len("/details"); len(elem) >= l && elem[0:l] == "/details" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetRelationsDetailsOperation
										r.summary = "Get user relations with visible activity details"
										r.operationID = "getRelationsDetails"
										r.operationGroup = ""
										r.pathPattern = "/api/relations/details"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							}

						case 'm': // Prefix: "move-friend"

							if l := len("move-friend"); len(elem) >= l && elem[0:l] == "move-friend" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = RemoveFriendOperation
									r.summary = "Remove a friend"
									r.operationID = "removeFriend"
									r.operationGroup = ""
									r.pathPattern = "/api/remove-friend"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 's': // Prefix: "s"
						origElem := elem
						if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "e"

							if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'a': // Prefix: "arch-tracks-via-details"

								if l := len("arch-tracks-via-details"); len(elem) >= l && elem[0:l] == "arch-tracks-via-details" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = SearchTracksViaDetailsOperation
										r.summary = "Search tracks via details"
										r.operationID = "searchTracksViaDetails"
										r.operationGroup = ""
										r.pathPattern = "/api/search-tracks-via-details"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 't': // Prefix: "t-"

								if l := len("t-"); len(elem) >= l && elem[0:l] == "t-" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "activity"

									if l := len("activity"); len(elem) >= l && elem[0:l] == "activity" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = SetActivityOperation
											r.summary = "Set current activity"
											r.operationID = "setActivity"
											r.operationGroup = ""
											r.pathPattern = "/api/set-activity"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

								case 'b': // Prefix: "b"

									if l := len("b"); len(elem) >= l && elem[0:l] == "b" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'e': // Prefix: "est-friend"

										if l := len("est-friend"); len(elem) >= l && elem[0:l] == "est-friend" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = SetBestFriendOperation
												r.summary = "Set or unset best friend"
												r.operationID = "setBestFriend"
												r.operationGroup = ""
												r.pathPattern = "/api/set-best-friend"
												r.args = args
												r.count = 0
												return r, true
											default:
												return
											}
										}

									case 'l': // Prefix: "locked"

										if l := len("locked"); len(elem) >= l && elem[0:l] == "locked" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = SetBlockedOperation
												r.summary = "Block or unblock a user"
												r.operationID = "setBlocked"
												r.operationGroup = ""
												r.pathPattern = "/api/set-blocked"
												r.args = args
												r.count = 0
												return r, true
											default:
												return
											}
										}

									}

								}

							}

						case 'i': // Prefix: "ignin"

							if l := len("ignin"); len(elem) >= l && elem[0:l] == "ignin" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = SignInOperation
									r.summary = "Sign in with email and password"
									r.operationID = "signIn"
									r.operationGroup = ""
									r.pathPattern = "/api/signin"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 't': // Prefix: "tatistics/"

							if l := len("tatistics/"); len(elem) >= l && elem[0:l] == "tatistics/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'g': // Prefix: "global/top/"

								if l := len("global/top/"); len(elem) >= l && elem[0:l] == "global/top/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'a': // Prefix: "a"

									if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										break
									}
									switch elem[0] {
									case 'l': // Prefix: "lbums"

										if l := len("lbums"); len(elem) >= l && elem[0:l] == "lbums" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = GetGlobalTopAlbumsOperation
												r.summary = "Get global top albums in the specified time range. Time range values default to the range of the previous full week starting on Friday."
												r.operationID = "getGlobalTopAlbums"
												r.operationGroup = ""
												r.pathPattern = "/api/statistics/global/top/albums"
												r.args = args
												r.count = 0
												return r, true
											default:
												return
											}
										}

									case 'r': // Prefix: "rtists"

										if l := len("rtists"); len(elem) >= l && elem[0:l] == "rtists" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "POST":
												r.name = GetGlobalTopArtistsOperation
												r.summary = "Get global top artists in the specified time range. Time range values default to the range of the previous full week starting on Friday."
												r.operationID = "getGlobalTopArtists"
												r.operationGroup = ""
												r.pathPattern = "/api/statistics/global/top/artists"
												r.args = args
												r.count = 0
												return r, true
											default:
												return
											}
										}

									}

								case 't': // Prefix: "tracks"

									if l := len("tracks"); len(elem) >= l && elem[0:l] == "tracks" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = GetGlobalTopTracksOperation
											r.summary = "Get global top tracks in the specified time range. Time range values default to the range of the previous full week starting on Friday."
											r.operationID = "getGlobalTopTracks"
											r.operationGroup = ""
											r.pathPattern = "/api/statistics/global/top/tracks"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

								}

							case 'u': // Prefix: "user/"

								if l := len("user/"); len(elem) >= l && elem[0:l] == "user/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'l': // Prefix: "listens/days"

									if l := len("listens/days"); len(elem) >= l && elem[0:l] == "listens/days" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = GetUserListensByDaysOperation
											r.summary = "Get user's listening information for the specified time range."
											r.operationID = "getUserListensByDays"
											r.operationGroup = ""
											r.pathPattern = "/api/statistics/user/listens/days"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

								case 't': // Prefix: "top/artist-plays"

									if l := len("top/artist-plays"); len(elem) >= l && elem[0:l] == "top/artist-plays" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = GetUserTopArtistPlayStatsOperation
											r.summary = "Get user's top artists with each artist's top tracks and albums."
											r.operationID = "getUserTopArtistPlayStats"
											r.operationGroup = ""
											r.pathPattern = "/api/statistics/user/top/artist-plays"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

								}

							}

						}

						elem = origElem
					case 't': // Prefix: "tracks/"
						origElem := elem
						if l := len("tracks/"); len(elem) >= l && elem[0:l] == "tracks/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "id"
						// Leaf parameter, slashes are prohibited
						idx := strings.IndexByte(elem, '/')
						if idx >= 0 {
							break
						}
						args[0] = elem
						elem = ""

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetTrackOperation
								r.summary = "Get track details"
								r.operationID = "getTrack"
								r.operationGroup = ""
								r.pathPattern = "/api/tracks/{id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

						elem = origElem
					case 'u': // Prefix: "user/"
						origElem := elem
						if l := len("user/"); len(elem) >= l && elem[0:l] == "user/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'd': // Prefix: "details"

							if l := len("details"); len(elem) >= l && elem[0:l] == "details" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetUserDetailsOperation
									r.summary = "Get current user details"
									r.operationID = "getUserDetails"
									r.operationGroup = ""
									r.pathPattern = "/api/user/details"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'i': // Prefix: "integrations"

							if l := len("integrations"); len(elem) >= l && elem[0:l] == "integrations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetUserIntegrationsOperation
									r.summary = "Get user integration details"
									r.operationID = "getUserIntegrations"
									r.operationGroup = ""
									r.pathPattern = "/api/user/integrations"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'u': // Prefix: "update"

							if l := len("update"); len(elem) >= l && elem[0:l] == "update" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = UpdateUserOperation
									r.summary = "Update user profile"
									r.operationID = "updateUser"
									r.operationGroup = ""
									r.pathPattern = "/api/user/update"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

						elem = origElem
					case 'v': // Prefix: "validate"
						origElem := elem
						if l := len("validate"); len(elem) >= l && elem[0:l] == "validate" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ValidateTokenOperation
								r.summary = "Validate authentication token"
								r.operationID = "validateToken"
								r.operationGroup = ""
								r.pathPattern = "/api/validate"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

						elem = origElem
					}
					// Param: "user_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case '/': // Prefix: "/calendar/listens"

						if l := len("/calendar/listens"); len(elem) >= l && elem[0:l] == "/calendar/listens" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = GetCalendarListensOperation
								r.summary = "Get calendar listens for user (ICS feed)"
								r.operationID = "getCalendarListens"
								r.operationGroup = ""
								r.pathPattern = "/api/{user_id}/calendar/listens"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				case 's': // Prefix: "syncapi.yaml"

					if l := len("syncapi.yaml"); len(elem) >= l && elem[0:l] == "syncapi.yaml" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetAsyncAPIOperation
							r.summary = "Get AsyncAPI schema."
							r.operationID = "getAsyncAPI"
							r.operationGroup = ""
							r.pathPattern = "/asyncapi.yaml"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'o': // Prefix: "openapi.yaml"

				if l := len("openapi.yaml"); len(elem) >= l && elem[0:l] == "openapi.yaml" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetOpenAPIOperation
						r.summary = "Get OpenAPI schema."
						r.operationID = "getOpenAPI"
						r.operationGroup = ""
						r.pathPattern = "/openapi.yaml"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
