// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddGroupRolesParams is parameters of AddGroupRoles operation.
type AddGroupRolesParams struct {
	GroupID uuid.UUID
}

func unpackAddGroupRolesParams(packed middleware.Parameters) (params AddGroupRolesParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAddGroupRolesParams(args [1]string, argsEscaped bool, r *http.Request) (params AddGroupRolesParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AddMessageReactionParams is parameters of addMessageReaction operation.
type AddMessageReactionParams struct {
	ConversationID uuid.UUID
	MessageID      uint64
	Emoji          string
}

func unpackAddMessageReactionParams(packed middleware.Parameters) (params AddMessageReactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "message_id",
			In:   "path",
		}
		params.MessageID = packed[key].(uint64)
	}
	{
		key := middleware.ParameterKey{
			Name: "emoji",
			In:   "path",
		}
		params.Emoji = packed[key].(string)
	}
	return params
}

func decodeAddMessageReactionParams(args [3]string, argsEscaped bool, r *http.Request) (params AddMessageReactionParams, _ error) {
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: message_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "message_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUint64(val)
				if err != nil {
					return err
				}

				params.MessageID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: emoji.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "emoji",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Emoji = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "emoji",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AddPlaylistTracksParams is parameters of addPlaylistTracks operation.
type AddPlaylistTracksParams struct {
	PlaylistID uuid.UUID
}

func unpackAddPlaylistTracksParams(packed middleware.Parameters) (params AddPlaylistTracksParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAddPlaylistTracksParams(args [1]string, argsEscaped bool, r *http.Request) (params AddPlaylistTracksParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteGroupParams is parameters of deleteGroup operation.
type DeleteGroupParams struct {
	GroupID uuid.UUID
}

func unpackDeleteGroupParams(packed middleware.Parameters) (params DeleteGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteGroupParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteGroupRoleParams is parameters of deleteGroupRole operation.
type DeleteGroupRoleParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func unpackDeleteGroupRoleParams(packed middleware.Parameters) (params DeleteGroupRoleParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteGroupRoleParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteGroupRoleParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: user_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "user_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteMessageParams is parameters of deleteMessage operation.
type DeleteMessageParams struct {
	ConversationID uuid.UUID
	MessageID      uint64
}

func unpackDeleteMessageParams(packed middleware.Parameters) (params DeleteMessageParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "message_id",
			In:   "path",
		}
		params.MessageID = packed[key].(uint64)
	}
	return params
}

func decodeDeleteMessageParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteMessageParams, _ error) {
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: message_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "message_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUint64(val)
				if err != nil {
					return err
				}

				params.MessageID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteMessageReactionParams is parameters of deleteMessageReaction operation.
type DeleteMessageReactionParams struct {
	ConversationID uuid.UUID
	MessageID      uint64
	Emoji          string
}

func unpackDeleteMessageReactionParams(packed middleware.Parameters) (params DeleteMessageReactionParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "message_id",
			In:   "path",
		}
		params.MessageID = packed[key].(uint64)
	}
	{
		key := middleware.ParameterKey{
			Name: "emoji",
			In:   "path",
		}
		params.Emoji = packed[key].(string)
	}
	return params
}

func decodeDeleteMessageReactionParams(args [3]string, argsEscaped bool, r *http.Request) (params DeleteMessageReactionParams, _ error) {
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: message_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "message_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUint64(val)
				if err != nil {
					return err
				}

				params.MessageID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: emoji.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "emoji",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Emoji = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "emoji",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeletePlaylistParams is parameters of deletePlaylist operation.
type DeletePlaylistParams struct {
	PlaylistID uuid.UUID
}

func unpackDeletePlaylistParams(packed middleware.Parameters) (params DeletePlaylistParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeletePlaylistParams(args [1]string, argsEscaped bool, r *http.Request) (params DeletePlaylistParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeletePlaylistRoleParams is parameters of deletePlaylistRole operation.
type DeletePlaylistRoleParams struct {
	PlaylistID uuid.UUID
	UserID     uuid.UUID
}

func unpackDeletePlaylistRoleParams(packed middleware.Parameters) (params DeletePlaylistRoleParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeletePlaylistRoleParams(args [2]string, argsEscaped bool, r *http.Request) (params DeletePlaylistRoleParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: user_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "user_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeletePlaylistTrackParams is parameters of deletePlaylistTrack operation.
type DeletePlaylistTrackParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

func unpackDeletePlaylistTrackParams(packed middleware.Parameters) (params DeletePlaylistTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "track_id",
			In:   "path",
		}
		params.TrackID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeletePlaylistTrackParams(args [2]string, argsEscaped bool, r *http.Request) (params DeletePlaylistTrackParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: track_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "track_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrackID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "track_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// EditGroupParams is parameters of editGroup operation.
type EditGroupParams struct {
	GroupID uuid.UUID
}

func unpackEditGroupParams(packed middleware.Parameters) (params EditGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeEditGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params EditGroupParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// EditMessageParams is parameters of editMessage operation.
type EditMessageParams struct {
	ConversationID uuid.UUID
	MessageID      uint64
}

func unpackEditMessageParams(packed middleware.Parameters) (params EditMessageParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "message_id",
			In:   "path",
		}
		params.MessageID = packed[key].(uint64)
	}
	return params
}

func decodeEditMessageParams(args [2]string, argsEscaped bool, r *http.Request) (params EditMessageParams, _ error) {
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: message_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "message_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUint64(val)
				if err != nil {
					return err
				}

				params.MessageID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// EditPlaylistParams is parameters of editPlaylist operation.
type EditPlaylistParams struct {
	PlaylistID uuid.UUID
}

func unpackEditPlaylistParams(packed middleware.Parameters) (params EditPlaylistParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeEditPlaylistParams(args [1]string, argsEscaped bool, r *http.Request) (params EditPlaylistParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// EditPlaylistRoleParams is parameters of editPlaylistRole operation.
type EditPlaylistRoleParams struct {
	PlaylistID uuid.UUID
	UserID     uuid.UUID
}

func unpackEditPlaylistRoleParams(packed middleware.Parameters) (params EditPlaylistRoleParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeEditPlaylistRoleParams(args [2]string, argsEscaped bool, r *http.Request) (params EditPlaylistRoleParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: user_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "user_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// EditPlaylistTrackParams is parameters of editPlaylistTrack operation.
type EditPlaylistTrackParams struct {
	PlaylistID uuid.UUID
	TrackID    uuid.UUID
}

func unpackEditPlaylistTrackParams(packed middleware.Parameters) (params EditPlaylistTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "track_id",
			In:   "path",
		}
		params.TrackID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeEditPlaylistTrackParams(args [2]string, argsEscaped bool, r *http.Request) (params EditPlaylistTrackParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: track_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "track_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrackID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "track_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetAlbumParams is parameters of getAlbum operation.
type GetAlbumParams struct {
	AlbumID uuid.UUID
}

func unpackGetAlbumParams(packed middleware.Parameters) (params GetAlbumParams) {
	{
		key := middleware.ParameterKey{
			Name: "album_id",
			In:   "path",
		}
		params.AlbumID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetAlbumParams(args [1]string, argsEscaped bool, r *http.Request) (params GetAlbumParams, _ error) {
	// Decode path: album_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "album_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.AlbumID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "album_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetArtistParams is parameters of getArtist operation.
type GetArtistParams struct {
	ArtistID uuid.UUID
}

func unpackGetArtistParams(packed middleware.Parameters) (params GetArtistParams) {
	{
		key := middleware.ParameterKey{
			Name: "artist_id",
			In:   "path",
		}
		params.ArtistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetArtistParams(args [1]string, argsEscaped bool, r *http.Request) (params GetArtistParams, _ error) {
	// Decode path: artist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "artist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ArtistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "artist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCalendarListensParams is parameters of getCalendarListens operation.
type GetCalendarListensParams struct {
	// The user whose calendar to retrieve.
	UserID uuid.UUID
	// The requesting user's ID (the viewer). Required if target user's visibility is not public.
	AuthID OptUUID `json:",omitempty,omitzero"`
	// HMAC token for authentication. Required if target user's visibility is not public.
	Token OptString `json:",omitempty,omitzero"`
}

func unpackGetCalendarListensParams(packed middleware.Parameters) (params GetCalendarListensParams) {
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "auth_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AuthID = v.(OptUUID)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "token",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Token = v.(OptString)
		}
	}
	return params
}

func decodeGetCalendarListensParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCalendarListensParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: user_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "user_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: auth_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "auth_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAuthIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotAuthIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AuthID.SetTo(paramsDotAuthIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "auth_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: token.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "token",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTokenVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotTokenVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Token.SetTo(paramsDotTokenVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "token",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetGroupParams is parameters of getGroup operation.
type GetGroupParams struct {
	GroupID uuid.UUID
}

func unpackGetGroupParams(packed middleware.Parameters) (params GetGroupParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetGroupParams(args [1]string, argsEscaped bool, r *http.Request) (params GetGroupParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetGroupRolesParams is parameters of getGroupRoles operation.
type GetGroupRolesParams struct {
	GroupID uuid.UUID
}

func unpackGetGroupRolesParams(packed middleware.Parameters) (params GetGroupRolesParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetGroupRolesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetGroupRolesParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetMessageThreadParams is parameters of getMessageThread operation.
type GetMessageThreadParams struct {
	ConversationID uuid.UUID
	MessageID      uint64
	Before         OptUint64 `json:",omitempty,omitzero"`
	Limit          OptInt    `json:",omitempty,omitzero"`
}

func unpackGetMessageThreadParams(packed middleware.Parameters) (params GetMessageThreadParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "message_id",
			In:   "path",
		}
		params.MessageID = packed[key].(uint64)
	}
	{
		key := middleware.ParameterKey{
			Name: "before",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Before = v.(OptUint64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeGetMessageThreadParams(args [2]string, argsEscaped bool, r *http.Request) (params GetMessageThreadParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: message_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "message_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUint64(val)
				if err != nil {
					return err
				}

				params.MessageID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: before.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBeforeVal uint64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUint64(val)
					if err != nil {
						return err
					}

					paramsDotBeforeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Before.SetTo(paramsDotBeforeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "before",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        false,
							Min:           0,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetMessagesParams is parameters of getMessages operation.
type GetMessagesParams struct {
	ConversationID uuid.UUID
	Before         OptUint64 `json:",omitempty,omitzero"`
	Limit          OptInt    `json:",omitempty,omitzero"`
}

func unpackGetMessagesParams(packed middleware.Parameters) (params GetMessagesParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "before",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Before = v.(OptUint64)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeGetMessagesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetMessagesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: before.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotBeforeVal uint64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUint64(val)
					if err != nil {
						return err
					}

					paramsDotBeforeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Before.SetTo(paramsDotBeforeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "before",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        false,
							Min:           0,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetPlaylistParams is parameters of getPlaylist operation.
type GetPlaylistParams struct {
	PlaylistID uuid.UUID
}

func unpackGetPlaylistParams(packed middleware.Parameters) (params GetPlaylistParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPlaylistParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPlaylistParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPlaylistRolesParams is parameters of getPlaylistRoles operation.
type GetPlaylistRolesParams struct {
	PlaylistID uuid.UUID
}

func unpackGetPlaylistRolesParams(packed middleware.Parameters) (params GetPlaylistRolesParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPlaylistRolesParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPlaylistRolesParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPlaylistTracksParams is parameters of getPlaylistTracks operation.
type GetPlaylistTracksParams struct {
	PlaylistID uuid.UUID
}

func unpackGetPlaylistTracksParams(packed middleware.Parameters) (params GetPlaylistTracksParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPlaylistTracksParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPlaylistTracksParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTrackParams is parameters of getTrack operation.
type GetTrackParams struct {
	TrackID uuid.UUID
}

func unpackGetTrackParams(packed middleware.Parameters) (params GetTrackParams) {
	{
		key := middleware.ParameterKey{
			Name: "track_id",
			In:   "path",
		}
		params.TrackID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetTrackParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTrackParams, _ error) {
	// Decode path: track_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "track_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrackID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "track_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserListenSessionsParams is parameters of getUserListenSessions operation.
type GetUserListenSessionsParams struct {
	Handle string
}

func unpackGetUserListenSessionsParams(packed middleware.Parameters) (params GetUserListenSessionsParams) {
	{
		key := middleware.ParameterKey{
			Name: "handle",
			In:   "path",
		}
		params.Handle = packed[key].(string)
	}
	return params
}

func decodeGetUserListenSessionsParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserListenSessionsParams, _ error) {
	// Decode path: handle.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "handle",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Handle = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "handle",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReadMessageParams is parameters of readMessage operation.
type ReadMessageParams struct {
	ConversationID uuid.UUID
	MessageID      uint64
}

func unpackReadMessageParams(packed middleware.Parameters) (params ReadMessageParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "message_id",
			In:   "path",
		}
		params.MessageID = packed[key].(uint64)
	}
	return params
}

func decodeReadMessageParams(args [2]string, argsEscaped bool, r *http.Request) (params ReadMessageParams, _ error) {
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: message_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "message_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUint64(val)
				if err != nil {
					return err
				}

				params.MessageID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "message_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SendMessageParams is parameters of sendMessage operation.
type SendMessageParams struct {
	ConversationID uuid.UUID
}

func unpackSendMessageParams(packed middleware.Parameters) (params SendMessageParams) {
	{
		key := middleware.ParameterKey{
			Name: "conversation_id",
			In:   "path",
		}
		params.ConversationID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSendMessageParams(args [1]string, argsEscaped bool, r *http.Request) (params SendMessageParams, _ error) {
	// Decode path: conversation_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "conversation_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ConversationID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "conversation_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SetPlaylistRolesParams is parameters of setPlaylistRoles operation.
type SetPlaylistRolesParams struct {
	PlaylistID uuid.UUID
}

func unpackSetPlaylistRolesParams(packed middleware.Parameters) (params SetPlaylistRolesParams) {
	{
		key := middleware.ParameterKey{
			Name: "playlist_id",
			In:   "path",
		}
		params.PlaylistID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSetPlaylistRolesParams(args [1]string, argsEscaped bool, r *http.Request) (params SetPlaylistRolesParams, _ error) {
	// Decode path: playlist_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "playlist_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PlaylistID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "playlist_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SubsonicDownloadParams is parameters of subsonicDownload operation.
type SubsonicDownloadParams struct {
	// Username.
	U string
	// Authentication token (MD5 hash of (password + salt)).
	T string
	// Salt used in token generation.
	S string
	// Subsonic API version.
	V string
	// Client application name.
	C string
	// Response format.
	F OptSubsonicAuthF `json:",omitempty,omitzero"`
	// Track ID.
	ID uuid.UUID
}

func unpackSubsonicDownloadParams(packed middleware.Parameters) (params SubsonicDownloadParams) {
	{
		key := middleware.ParameterKey{
			Name: "u",
			In:   "query",
		}
		params.U = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "t",
			In:   "query",
		}
		params.T = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "s",
			In:   "query",
		}
		params.S = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "v",
			In:   "query",
		}
		params.V = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "c",
			In:   "query",
		}
		params.C = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "f",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.F = v.(OptSubsonicAuthF)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "query",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeSubsonicDownloadParams(args [0]string, argsEscaped bool, r *http.Request) (params SubsonicDownloadParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: u.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "u",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.U = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "u",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: t.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "t",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.T = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "t",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: s.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "s",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.S = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "s",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: v.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "v",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.V = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "v",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: c.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "c",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.C = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "c",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: f.
	{
		val := SubsonicAuthF("xml")
		params.F.SetTo(val)
	}
	// Decode query: f.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "f",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFVal SubsonicAuthF
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFVal = SubsonicAuthF(c)
					return nil
				}(); err != nil {
					return err
				}
				params.F.SetTo(paramsDotFVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.F.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "f",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SubsonicStreamParams is parameters of subsonicStream operation.
type SubsonicStreamParams struct {
	// Username.
	U string
	// Authentication token (MD5 hash of (password + salt)).
	T string
	// Salt used in token generation.
	S string
	// Subsonic API version.
	V string
	// Client application name.
	C string
	// Response format.
	F OptSubsonicAuthF `json:",omitempty,omitzero"`
	// Track ID.
	ID uuid.UUID
	// Maximum bitrate in kbps, 0 meaning unlimited.
	MaxBitRate OptSubsonicStreamMaxBitRate `json:",omitempty,omitzero"`
	// Target transcode format.
	Format OptSubsonicStreamFormat `json:",omitempty,omitzero"`
	// Start streaming from this offset in seconds.
	TimeOffset OptInt `json:",omitempty,omitzero"`
	// Include an estimated Content-Length header.
	EstimateContentLength OptBool `json:",omitempty,omitzero"`
}

func unpackSubsonicStreamParams(packed middleware.Parameters) (params SubsonicStreamParams) {
	{
		key := middleware.ParameterKey{
			Name: "u",
			In:   "query",
		}
		params.U = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "t",
			In:   "query",
		}
		params.T = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "s",
			In:   "query",
		}
		params.S = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "v",
			In:   "query",
		}
		params.V = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "c",
			In:   "query",
		}
		params.C = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "f",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.F = v.(OptSubsonicAuthF)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "query",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "maxBitRate",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.MaxBitRate = v.(OptSubsonicStreamMaxBitRate)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "format",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Format = v.(OptSubsonicStreamFormat)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "timeOffset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.TimeOffset = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "estimateContentLength",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EstimateContentLength = v.(OptBool)
		}
	}
	return params
}

func decodeSubsonicStreamParams(args [0]string, argsEscaped bool, r *http.Request) (params SubsonicStreamParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: u.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "u",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.U = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "u",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: t.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "t",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.T = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "t",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: s.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "s",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.S = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "s",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: v.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "v",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.V = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "v",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: c.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "c",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.C = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "c",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: f.
	{
		val := SubsonicAuthF("xml")
		params.F.SetTo(val)
	}
	// Decode query: f.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "f",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFVal SubsonicAuthF
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFVal = SubsonicAuthF(c)
					return nil
				}(); err != nil {
					return err
				}
				params.F.SetTo(paramsDotFVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.F.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "f",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: maxBitRate.
	{
		val := SubsonicStreamMaxBitRate(0)
		params.MaxBitRate.SetTo(val)
	}
	// Decode query: maxBitRate.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "maxBitRate",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotMaxBitRateVal SubsonicStreamMaxBitRate
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotMaxBitRateVal = SubsonicStreamMaxBitRate(c)
					return nil
				}(); err != nil {
					return err
				}
				params.MaxBitRate.SetTo(paramsDotMaxBitRateVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.MaxBitRate.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "maxBitRate",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: format.
	{
		val := SubsonicStreamFormat("mp3")
		params.Format.SetTo(val)
	}
	// Decode query: format.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "format",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFormatVal SubsonicStreamFormat
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotFormatVal = SubsonicStreamFormat(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Format.SetTo(paramsDotFormatVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Format.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "format",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: timeOffset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "timeOffset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotTimeOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotTimeOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.TimeOffset.SetTo(paramsDotTimeOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.TimeOffset.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "timeOffset",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: estimateContentLength.
	{
		val := bool(false)
		params.EstimateContentLength.SetTo(val)
	}
	// Decode query: estimateContentLength.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "estimateContentLength",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEstimateContentLengthVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotEstimateContentLengthVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.EstimateContentLength.SetTo(paramsDotEstimateContentLengthVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "estimateContentLength",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateGroupRolesParams is parameters of UpdateGroupRoles operation.
type UpdateGroupRolesParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func unpackUpdateGroupRolesParams(packed middleware.Parameters) (params UpdateGroupRolesParams) {
	{
		key := middleware.ParameterKey{
			Name: "group_id",
			In:   "path",
		}
		params.GroupID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "path",
		}
		params.UserID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateGroupRolesParams(args [2]string, argsEscaped bool, r *http.Request) (params UpdateGroupRolesParams, _ error) {
	// Decode path: group_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "group_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GroupID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "group_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: user_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "user_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UploadTrackAudioParams is parameters of uploadTrackAudio operation.
type UploadTrackAudioParams struct {
	TrackID uuid.UUID
}

func unpackUploadTrackAudioParams(packed middleware.Parameters) (params UploadTrackAudioParams) {
	{
		key := middleware.ParameterKey{
			Name: "track_id",
			In:   "path",
		}
		params.TrackID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUploadTrackAudioParams(args [1]string, argsEscaped bool, r *http.Request) (params UploadTrackAudioParams, _ error) {
	// Decode path: track_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "track_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.TrackID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "track_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
