// Code generated by ogen, DO NOT EDIT.
package openapi

type AddFriendRes interface {
	addFriendRes()
}

type AddGroupRolesRes interface {
	addGroupRolesRes()
}

type AddMessageReactionRes interface {
	addMessageReactionRes()
}

type AddPlaylistTracksRes interface {
	addPlaylistTracksRes()
}

type AddToLibraryRes interface {
	addToLibraryRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreatePlaylistRes interface {
	createPlaylistRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteGroupRoleRes interface {
	deleteGroupRoleRes()
}

type DeleteMessageReactionRes interface {
	deleteMessageReactionRes()
}

type DeleteMessageRes interface {
	deleteMessageRes()
}

type DeletePlaylistRes interface {
	deletePlaylistRes()
}

type DeletePlaylistRoleRes interface {
	deletePlaylistRoleRes()
}

type DeletePlaylistTrackRes interface {
	deletePlaylistTrackRes()
}

type EditGroupRes interface {
	editGroupRes()
}

type EditMessageRes interface {
	editMessageRes()
}

type EditPlaylistRes interface {
	editPlaylistRes()
}

type EditPlaylistRoleRes interface {
	editPlaylistRoleRes()
}

type EditPlaylistTrackRes interface {
	editPlaylistTrackRes()
}

type GetAlbumRes interface {
	getAlbumRes()
}

type GetArtistRes interface {
	getArtistRes()
}

type GetCalendarListensRes interface {
	getCalendarListensRes()
}

type GetGlobalTopAlbumsRes interface {
	getGlobalTopAlbumsRes()
}

type GetGlobalTopArtistsRes interface {
	getGlobalTopArtistsRes()
}

type GetGlobalTopTracksRes interface {
	getGlobalTopTracksRes()
}

type GetGroupRes interface {
	getGroupRes()
}

type GetGroupRolesRes interface {
	getGroupRolesRes()
}

type GetGroupsRes interface {
	getGroupsRes()
}

type GetLibraryAlbumsRes interface {
	getLibraryAlbumsRes()
}

type GetLibraryArtistsRes interface {
	getLibraryArtistsRes()
}

type GetLibraryPlaylistsRes interface {
	getLibraryPlaylistsRes()
}

type GetLibrarySearchIndexRes interface {
	getLibrarySearchIndexRes()
}

type GetLibraryTracksRes interface {
	getLibraryTracksRes()
}

type GetListenSessionsRes interface {
	getListenSessionsRes()
}

type GetMessageThreadRes interface {
	getMessageThreadRes()
}

type GetMessagesRes interface {
	getMessagesRes()
}

type GetPlaylistRes interface {
	getPlaylistRes()
}

type GetPlaylistRolesRes interface {
	getPlaylistRolesRes()
}

type GetPlaylistTracksRes interface {
	getPlaylistTracksRes()
}

type GetRelationsDetailsRes interface {
	getRelationsDetailsRes()
}

type GetTrackRes interface {
	getTrackRes()
}

type GetTracksPlayStatsRes interface {
	getTracksPlayStatsRes()
}

type GetUserDetailsRes interface {
	getUserDetailsRes()
}

type GetUserIntegrationsRes interface {
	getUserIntegrationsRes()
}

type GetUserListenSessionsRes interface {
	getUserListenSessionsRes()
}

type GetUserListensByDaysRes interface {
	getUserListensByDaysRes()
}

type GetUserRelationsRes interface {
	getUserRelationsRes()
}

type GetUserTopArtistPlayStatsRes interface {
	getUserTopArtistPlayStatsRes()
}

type JoinFreeBetaRes interface {
	joinFreeBetaRes()
}

type ReadMessageRes interface {
	readMessageRes()
}

type RegisterRes interface {
	registerRes()
}

type RemoveFriendRes interface {
	removeFriendRes()
}

type RemoveFromLibraryRes interface {
	removeFromLibraryRes()
}

type SearchTracksRes interface {
	searchTracksRes()
}

type SendMessageRes interface {
	sendMessageRes()
}

type SetActivityRes interface {
	setActivityRes()
}

type SetBestFriendRes interface {
	setBestFriendRes()
}

type SetBlockedRes interface {
	setBlockedRes()
}

type SetPlaylistRolesRes interface {
	setPlaylistRolesRes()
}

type SignInRes interface {
	signInRes()
}

type SubsonicDownloadRes interface {
	subsonicDownloadRes()
}

type SubsonicStreamRes interface {
	subsonicStreamRes()
}

type UpdateGroupRolesRes interface {
	updateGroupRolesRes()
}

type UpdateLibraryRes interface {
	updateLibraryRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UploadTrackAudioRes interface {
	uploadTrackAudioRes()
}

type ValidateTokenRes interface {
	validateTokenRes()
}
