// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddFriend implements addFriend operation.
//
// Add a friend.
//
// POST /api/add-friend
func (UnimplementedHandler) AddFriend(ctx context.Context, req *FriendActionRequest) (r AddFriendRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddToLibrary implements addToLibrary operation.
//
// Add items to library.
//
// POST /api/library/add
func (UnimplementedHandler) AddToLibrary(ctx context.Context, req *LibraryAddRequest) (r AddToLibraryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAlbum implements getAlbum operation.
//
// Get album details.
//
// GET /api/albums/{id}
func (UnimplementedHandler) GetAlbum(ctx context.Context, params GetAlbumParams) (r GetAlbumRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetArtist implements getArtist operation.
//
// Get artist details.
//
// GET /api/artists/{id}
func (UnimplementedHandler) GetArtist(ctx context.Context, params GetArtistParams) (r GetArtistRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCalendarListens implements getCalendarListens operation.
//
// Serves listening history as an ICS feed. Access respects requested user's privacy settings. If
// requested user's privacy is not public, auth and token params are required.
//
// GET /api/{user_id}/calendar/listens
func (UnimplementedHandler) GetCalendarListens(ctx context.Context, params GetCalendarListensParams) (r GetCalendarListensRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLibraryMetadata implements getLibraryMetadata operation.
//
// Get library metadata.
//
// GET /api/library/get-metadata
func (UnimplementedHandler) GetLibraryMetadata(ctx context.Context) (r GetLibraryMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetListenSessions implements getListenSessions operation.
//
// Get recent listening sessions.
//
// POST /api/listens/sessions
func (UnimplementedHandler) GetListenSessions(ctx context.Context, req *ListensSessionsRequest) (r GetListenSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRelations implements getRelations operation.
//
// Get user relations.
//
// GET /api/relations
func (UnimplementedHandler) GetRelations(ctx context.Context) (r GetRelationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRelationsDetails implements getRelationsDetails operation.
//
// Get user relations with visible activity details.
//
// GET /api/relations/details
func (UnimplementedHandler) GetRelationsDetails(ctx context.Context) (r GetRelationsDetailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrack implements getTrack operation.
//
// Get track details.
//
// GET /api/tracks/{id}
func (UnimplementedHandler) GetTrack(ctx context.Context, params GetTrackParams) (r GetTrackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserDetails implements getUserDetails operation.
//
// Get current user details.
//
// GET /api/user/details
func (UnimplementedHandler) GetUserDetails(ctx context.Context) (r GetUserDetailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserListenSessions implements getUserListenSessions operation.
//
// Get listen sessions for another user.
//
// POST /api/@{handle}/listens/sessions
func (UnimplementedHandler) GetUserListenSessions(ctx context.Context, req *ListensSessionsRequest, params GetUserListenSessionsParams) (r GetUserListenSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// JoinFreeBeta implements joinFreeBeta operation.
//
// Join free beta.
//
// POST /api/join-free-beta
func (UnimplementedHandler) JoinFreeBeta(ctx context.Context) (r JoinFreeBetaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Register implements register operation.
//
// Register a new user.
//
// POST /api/register
func (UnimplementedHandler) Register(ctx context.Context, req *RegisterRequest) (r RegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveFriend implements removeFriend operation.
//
// Remove a friend.
//
// POST /api/remove-friend
func (UnimplementedHandler) RemoveFriend(ctx context.Context, req *RemoveFriendReq) (r RemoveFriendRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveFromLibrary implements removeFromLibrary operation.
//
// Remove items from library.
//
// POST /api/library/remove
func (UnimplementedHandler) RemoveFromLibrary(ctx context.Context, req *LibraryRemoveRequest) (r RemoveFromLibraryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchTracksViaDetails implements searchTracksViaDetails operation.
//
// Search tracks via details.
//
// POST /api/search-tracks-via-details
func (UnimplementedHandler) SearchTracksViaDetails(ctx context.Context, req *SearchTracksRequest) (r SearchTracksViaDetailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetActivity implements setActivity operation.
//
// Set current activity.
//
// POST /api/set-activity
func (UnimplementedHandler) SetActivity(ctx context.Context, req []SetActivityItem) (r SetActivityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetBestFriend implements setBestFriend operation.
//
// Set or unset best friend.
//
// POST /api/set-best-friend
func (UnimplementedHandler) SetBestFriend(ctx context.Context, req *BestFriendActionRequest) (r SetBestFriendRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetBlocked implements setBlocked operation.
//
// Block or unblock a user.
//
// POST /api/set-blocked
func (UnimplementedHandler) SetBlocked(ctx context.Context, req *BlockedActionRequest) (r SetBlockedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SignIn implements signIn operation.
//
// Sign in with email and password.
//
// POST /api/signin
func (UnimplementedHandler) SignIn(ctx context.Context, req *SignInRequest) (r SignInRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateLibrary implements updateLibrary operation.
//
// Update items in library.
//
// POST /api/library/update
func (UnimplementedHandler) UpdateLibrary(ctx context.Context, req *LibraryUpdateRequest) (r UpdateLibraryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements updateUser operation.
//
// Update user profile.
//
// POST /api/user/update
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *UpdateUserRequest) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateToken implements validateToken operation.
//
// Validate authentication token.
//
// GET /api/validate
func (UnimplementedHandler) ValidateToken(ctx context.Context) (r ValidateTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}
