openapi: 3.0.0

info:
  title: Echoes
  description: HTTP API
  version: 1.0.0
  license:
    name: Proprietary

servers:
  - url: https://echoes.la
    description: Production server.
    x-ogen-server-name: Production
