// Code generated by go-asyncapi tool. DO NOT EDIT.

package wss

import (
	"context"
	"github.com/bdragon300/go-asyncapi/run"
	"io"
)

// Pub
type (
	Producer interface {
		Publisher(ctx context.Context, address string, security run.AnySecurityScheme) (Publisher, error)
	}
	Publisher interface {
		Send(ctx context.Context, envelopes ...EnvelopeWriter) error
		Close() error
	}
	EnvelopeWriter interface {
		io.Writer
		ResetPayload()
		SetHeaders(headers run.Headers)
		SetContentType(contentType string)
	}
)

// Sub
type (
	Consumer interface {
		Subscriber(ctx context.Context, address string, security run.AnySecurityScheme) (Subscriber, error)
	}
	Subscriber interface {
		Receive(ctx context.Context, cb func(envelope EnvelopeReader)) error
		Close() error
	}
	EnvelopeReader interface {
		io.Reader
		Headers() run.Headers
	}
)
